; OPcache Configuration
opcache.enable = 1
opcache.memory_consumption=8196M
opcache.interned_strings_buffer=256M
opcache.max_accelerated_files=60000
opcache.revalidate_freq=20
opcache.enable_cli=1
opcache.jit_buffer_size=512M
opcache.jit=1255
opcache.validate_timestamps=0
opcache.save_comments=1
opcache.file_update_protection=0
opcache.max_file_size=0
; opcache.protect_memory=0
opcache.error_log=/var/www/html/wp-content/debug/opcache_error.log
; Advanced JIT optimizations for better performance
opcache.jit_prof_threshold=0.001
opcache.jit_max_root_traces=8196
opcache.jit_max_side_traces=1024
opcache.jit_hot_func=255
opcache.jit_max_loop_unrolls=9
opcache.jit_max_polymorphic_calls=4