xdebug.mode=debug
# xdebug.mode=debug,profile,trace
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9004
xdebug.discover_client_host=1
xdebug.log_level=1
xdebug.log=/var/www/html/wp-content/debug/xdebug/xdebug.log
; Output directory for profiles and traces
xdebug.output_dir=/var/www/html/wp-content/debug/xdebug
; Profiling settings
xdebug.profiler_output_name=cachegrind.out.%p.%H.%R ; Open with KCacheGrind or similar tool
; Tracing settings
xdebug.trace_output_name=trace.%p.%H.%R