import type { JobSchemaResponse, WPBasePost } from "@/types";
import { isNil } from "es-toolkit";
import { type APIServiceServer } from "@/services/graphql/APIService";

/**
 * Attaches a JSON-LD schema script to the HTML.
 * @param schema Normalized url as JSON string to be injected into the script tag. Should be generated by @see schemaScriptParser first.
 * @param ldType The type of the JSON-LD schema (e.g., "JobPosting", "ItemList")
 * @param ldId WP post ID as unique identifier for the schema
 * @returns 
 */
export function schemaScriptAttach(
	schema: ReturnType<typeof schemaScriptParser>,
	ldType: JobSchemaResponse[ "type" ],
	ldId?: WPBasePost[ "id" ],
)
{
	if (!schema) return "";

	const dataAttrs = `data-ld-type="${ldType}"`;
	const type = ldType ? ldType.toLowerCase() : null;
	const idAttr = ldId ? `data-ld-id="${type}-${ldId}"` : "";

	return String.raw /*html*/`<script type="application/ld+json" ${dataAttrs} ${idAttr}>${schema}</script>`;
}

/**
 * Since schema contain array of JSON string, it needs to be parsed first before normalizing the URLs in SSR load functions.
 * @param schema received from @see APIServiceServer.fetchJobSchemasGraphQL, which is an array of JSON strings or nulls.
 * @returns the first parsed schema or null if none are available
 */
export function schemaScriptParser(schema: Awaited<ReturnType<typeof APIServiceServer.fetchJobSchemasGraphQL>>): string | null
{
	if (!schema) return null;
	const parsedSchemas: string[] = schema
		.filter((s) => !isNil(s))
		.map((s) => JSON.parse(s)) || [];
	const jobSchema = Array.isArray(parsedSchemas) ? parsedSchemas[ 0 ] : null;
	return jobSchema;
}

/**
 * *Use Embedded Language for better DX or switch LSP to html.
 * 
 * This script is used to apply the user's theme preference (dark/light) as early as possible to prevent FOUC. It checks localStorage for a saved theme, falls back to system preference, and applies the theme by setting a data attribute on the root element. After execution, it removes itself from the DOM.
 */
export const inlineScript = (String.raw /*html*/`<script id="wplokerbjm-theme-inline-script">
	(() => {
		const cleanUp = () => {
			const el = document.getElementById("wplokerbjm-theme-inline-script");
			if (el) {
				el.remove();
			}
		};

		try {
			const KEY = "wplokerbjm-theme";
			const root = document.documentElement;
			let stored = null;
			try {
				stored = localStorage.getItem(KEY);
			} catch (e) {
				stored = null;
			}
			const apply = (theme) => {
				if (!theme) return;
				root.setAttribute("data-theme", theme);
				root.classList.toggle("wplokerbjm-dark-mode-enable", theme === "dark");
			};
			if (["dark", "light", "lavender"].indexOf(stored) !== -1) {
				apply(stored);
				return;
			}
			let prefersDark = false;
			try {
				prefersDark =
					window.matchMedia?.("(prefers-color-scheme: dark)")?.matches ?? false;
			} catch {}
			const chosen = prefersDark ? "dark" : "light";
			apply(chosen);
		} catch (e) {
			console.log("fail applying theme preferences", e);
		} finally {
			cleanUp();
		}
	})();
	</script>`);