import { isNil } from "es-toolkit";
//eslint-disable-next-line
import type { JobSchemaResponse, WPBasePost } from "@/types";
import { type APIServiceServer } from "@/services/graphql/APIService";

/**
 * Attaches a JSON-LD schema script to the HTML.
 * @param schema Normalized url as JSON string to be injected into the script tag. Should be generated by @see schemaScriptParser first.
 * @param ldType The type of the JSON-LD schema (e.g., "JobPosting", "ItemList")
 * @param ldId WP post ID as unique identifier for the schema
 */
export async function schemaScriptAttach(
	schema: ReturnType<typeof schemaScriptParser>,
	ldType: JobSchemaResponse[ "type" ],
	ldId?: WPBasePost[ "id" ],
)
{
	if (!schema) return "";

	const dataAttrs = `data-ld-type="${ldType}"`;
	const type = ldType ? ldType.toLowerCase() : null;
	const idAttr = ldId ? `data-ld-id="${type}-${ldId}"` : "";

	return String.raw /*html*/ `<script type="application/ld+json" ${dataAttrs} ${idAttr}>${schema}</script>`;
}

/**
 * Since schema contain array of JSON string, it needs to be parsed first before normalizing the URLs in SSR load functions.
 * @param schema received from @see APIServiceServer.fetchJobSchemasGraphQL, which is an array of JSON strings or nulls.
 * @returns the first parsed schema or null if none are available
 */
export function schemaScriptParser(
	schema: Awaited<ReturnType<typeof APIServiceServer.fetchJobSchemasGraphQL>>,
): string | null
{
	if (!schema) return null;
	const parsedSchemas: string[] =
		schema.filter((s) => !isNil(s)).map((s) => JSON.parse(s)) || [];
	const jobSchema = Array.isArray(parsedSchemas) ? parsedSchemas[ 0 ] : null;
	return jobSchema;
}