services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${WP_ENV}
    container_name: wordpress-${WP_ENV}
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: true
      WP_ENV: ${WP_ENV}
      WP_REPAIR: "false"
      FORCE_SSL_ADMIN: "true"
      WP_HOME: ${WORDPRESS_WP_HOME}
      WP_SITEURL: ${WORDPRESS_WP_SITEURL}
      WORDPRESS_CONFIG_EXTRA: |
        include('/var/www/html/wp-config-extra.php');
    volumes:
      - ./wordpress:/var/www/html
      - ./configs/wp-config-extra.php:/var/www/html/wp-config-extra.php:ro
      - ./certs/localhost.crt:/var/www/certs/localhost.crt:ro
      - sock:/var/run/sock
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm > /dev/null || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  caddy:
    build:
      context: .
      dockerfile: caddy.Dockerfile
    container_name: caddy
    environment:
      WP_ENV: ${WP_ENV}
      REDIS_PWD: ${REDIS_PWD}
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "443:443/udp"
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./configs/caddy-early-hints.conf:/etc/caddy/caddy-early-hints.conf:ro
      - ./certs/localhost.crt:/var/www/certs/localhost.crt:ro
      - ./certs/localhost.key:/var/www/certs/localhost.key:ro
      - sock:/var/run/sock:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:latest
    container_name: wordpress_db
    command: --socket=/var/run/sock/mysql.sock --port=3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - db:/var/lib/mysql
      - sock:/var/run/sock
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -S /var/run/sock/mysql.sock -u$$MYSQL_USER -p$$MYSQL_PASSWORD || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      PMA_ARBITRARY: 1
      APACHE_PORT: 81
    ports:
      - "81:81"
    depends_on:
      - db
  redis:
    image: redis:latest
    env_file:
      - ./.env
    container_name: wordpress_redis
    command: sh -c "mkdir -p /var/run/sock && chmod 777 /var/run/sock && redis-server --requirepass ${REDIS_PWD} --maxmemory ${REDIS_MAXMEMORY} --maxmemory-policy ${REDIS_MAXMEMORY_POLICY} --port ${REDIS_PORT} --unixsocket /var/run/sock/redis.sock --unixsocketperm 777"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - sock:/var/run/sock

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
      CLOUDFLARE_RECORD_NAME: ${CLOUDFLARE_RECORD_NAME}
      TUNNEL_ID: ${CLOUDFLARE_TUNNEL_ID}
    volumes:
      - ./configs/cloudflared-config.yml:/etc/cloudflared/config.yml:ro
    command: tunnel --config /etc/cloudflared/config.yml run
    depends_on:
      - caddy
    profiles:
      - online

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   container_name: ngrok
  #   command: http caddy:443
  #   environment:
  #     - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
  #   ports:
  #     - "4040:4040"
  #   depends_on:
  #     - caddy

volumes:
  db:
  sock:
