<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'AstraChild\\Controllers\\REST\\LoadMore' => 'get1',
  'subEntry1' => 'get2',
  'AstraChild\\Controllers\\REST\\Carousel' => 'get3',
  'subEntry2' => 'get4',
  'AstraChild\\Controllers\\REST\\AutoSuggestionSearch' => 'get5',
  'AstraChild\\Controllers\\REST\\DynamicSearch' => 'get6',
  'subEntry3' => 'get7',
  'AstraChild\\Controllers\\REST\\SingleOverlay' => 'get8',
  'subEntry4' => 'get9',
  'AstraChild\\Controllers\\REST\\TaxonomyDepth' => 'get10',
  'subEntry5' => 'get11',
  'subEntry6' => 'get12',
  'AstraChild\\Repositories\\CustomFieldRepository' => 'get13',
  'AstraChild\\Repositories\\JobRepository' => 'get14',
  'subEntry7' => 'get15',
  'subEntry8' => 'get16',
  'subEntry9' => 'get17',
  'AstraChild\\Repositories\\TaxonomyRepository' => 'get18',
  'AstraChild\\Models\\TaxonomyEntity' => 'get19',
  'AstraChild\\Models\\Schema\\PostTypes' => 'get20',
  'AstraChild\\Models\\Schema\\CustomFields' => 'get21',
  'AstraChild\\Models\\Schema\\Taxonomies' => 'get22',
  'AstraChild\\Services\\PostsManagement\\PostsManagement' => 'get23',
  'AstraChild\\Services\\Taxonomy\\TaxonomyService' => 'get24',
  'AstraChild\\Services\\Taxonomy\\TaxonomyManagement' => 'get25',
  'AstraChild\\Services\\CustomField\\CustomFieldsService' => 'get26',
  'AstraChild\\Services\\REST\\RESTData' => 'get27',
  'subEntry10' => 'get28',
  'AstraChild\\Services\\REST\\RESTRoute' => 'get29',
  'subEntry11' => 'get30',
  'subEntry12' => 'get31',
  'subEntry13' => 'get32',
  'subEntry14' => 'get33',
  'subEntry15' => 'get34',
  'subEntry16' => 'get35',
  'AstraChild\\Services\\Job\\JobServices' => 'get36',
  'subEntry17' => 'get37',
  'AstraChild\\Services\\Job\\ArchiveServices' => 'get38',
  'AstraChild\\Layouts\\Layouts' => 'get39',
  'AstraChild\\Components\\JobCarousel' => 'get40',
  'subEntry18' => 'get41',
  'AstraChild\\Components\\Hero' => 'get42',
  'AstraChild\\Components\\JobGrid' => 'get43',
  'subEntry19' => 'get44',
  'subEntry20' => 'get45',
  'AstraChild\\ViewModels\\Page\\HomepageViewModel' => 'get46',
  'subEntry21' => 'get47',
  'subEntry22' => 'get48',
  'subEntry23' => 'get49',
  'subEntry24' => 'get50',
  'subEntry25' => 'get51',
  'AstraChild\\ViewModels\\Page\\ArchiveViewModel' => 'get52',
  'subEntry26' => 'get53',
  'subEntry27' => 'get54',
  'subEntry28' => 'get55',
  'subEntry29' => 'get56',
  'AstraChild\\Views\\Page\\HomepageView' => 'get57',
  'subEntry30' => 'get58',
  'AstraChild\\Views\\Page\\SingleView' => 'get59',
  'subEntry31' => 'get60',
  'subEntry32' => 'get61',
  'subEntry33' => 'get62',
  'AstraChild\\Views\\Page\\ArchiveView' => 'get63',
  'subEntry34' => 'get64',
  'AstraChild\\Views\\Page\\PasangIklanView' => 'get65',
  'subEntry35' => 'get66',
  'AstraChild\\Core\\Enqueue\\Vite' => 'get67',
  'AstraChild\\Core\\Hooks' => 'get68',
  'AstraChild\\Core\\Enqueue' => 'get69',
  'subEntry36' => 'get70',
  'AstraChild\\Core\\Init' => 'get71',
  'customFieldsProvider' => 'get72',
  'taxonomiesProvider' => 'get73',
  'AstraChild\\Factories\\JobDataFactory' => 'get74',
  'subEntry37' => 'get75',
  'subEntry38' => 'get76',
  'subEntry39' => 'get77',
  'subEntry40' => 'get78',
  'AstraChild\\QueryBuilders\\JobQuery' => 'get79',
);

    protected function get2()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\JobRepository');
    }

    protected function get1()
    {
        $object = new AstraChild\Controllers\REST\LoadMore($this->get2());
        return $object;
    }

    protected function get4()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\JobRepository');
    }

    protected function get3()
    {
        $object = new AstraChild\Controllers\REST\Carousel($this->get4());
        return $object;
    }

    protected function get5()
    {
        $object = new AstraChild\Controllers\REST\AutoSuggestionSearch();
        return $object;
    }

    protected function get7()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\JobRepository');
    }

    protected function get6()
    {
        $object = new AstraChild\Controllers\REST\DynamicSearch($this->get7());
        return $object;
    }

    protected function get9()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\REST\\RESTData');
    }

    protected function get8()
    {
        $object = new AstraChild\Controllers\REST\SingleOverlay($this->get9());
        return $object;
    }

    protected function get11()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\Taxonomy\\TaxonomyService');
    }

    protected function get12()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\TaxonomyRepository');
    }

    protected function get10()
    {
        $object = new AstraChild\Controllers\REST\TaxonomyDepth($this->get11(), $this->get12());
        return $object;
    }

    protected function get13()
    {
        $object = new AstraChild\Repositories\CustomFieldRepository();
        return $object;
    }

    protected function get15()
    {
        return $this->delegateContainer->get('AstraChild\\Factories\\JobDataFactory');
    }

    protected function get16()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\REST\\RESTData');
    }

    protected function get17()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\Job\\JobServices');
    }

    protected function get14()
    {
        $object = new AstraChild\Repositories\JobRepository($this->get15(), $this->get16(), $this->get17());
        return $object;
    }

    protected function get18()
    {
        $object = new AstraChild\Repositories\TaxonomyRepository();
        return $object;
    }

    protected function get19()
    {
        $object = new AstraChild\Models\TaxonomyEntity(NULL, NULL, NULL, NULL, NULL, NULL);
        return $object;
    }

    protected function get20()
    {
        $object = new AstraChild\Models\Schema\PostTypes();
        return $object;
    }

    protected function get21()
    {
        $object = new AstraChild\Models\Schema\CustomFields();
        return $object;
    }

    protected function get22()
    {
        $object = new AstraChild\Models\Schema\Taxonomies();
        return $object;
    }

    protected function get23()
    {
        $object = new AstraChild\Services\PostsManagement\PostsManagement();
        return $object;
    }

    protected function get24()
    {
        $object = new AstraChild\Services\Taxonomy\TaxonomyService();
        return $object;
    }

    protected function get25()
    {
        $object = new AstraChild\Services\Taxonomy\TaxonomyManagement();
        return $object;
    }

    protected function get26()
    {
        $object = new AstraChild\Services\CustomField\CustomFieldsService();
        return $object;
    }

    protected function get28()
    {
        return $this->delegateContainer->get('AstraChild\\Factories\\JobDataFactory');
    }

    protected function get27()
    {
        $object = new AstraChild\Services\REST\RESTData($this->get28());
        return $object;
    }

    protected function get30()
    {
        return $this->delegateContainer->get('AstraChild\\Controllers\\REST\\TaxonomyDepth');
    }

    protected function get31()
    {
        return $this->delegateContainer->get('AstraChild\\Controllers\\REST\\AutoSuggestionSearch');
    }

    protected function get32()
    {
        return $this->delegateContainer->get('AstraChild\\Controllers\\REST\\LoadMore');
    }

    protected function get33()
    {
        return $this->delegateContainer->get('AstraChild\\Controllers\\REST\\DynamicSearch');
    }

    protected function get34()
    {
        return $this->delegateContainer->get('AstraChild\\Controllers\\REST\\Carousel');
    }

    protected function get35()
    {
        return $this->delegateContainer->get('AstraChild\\Controllers\\REST\\SingleOverlay');
    }

    protected function get29()
    {
        $object = new AstraChild\Services\REST\RESTRoute($this->get30(), $this->get31(), $this->get32(), $this->get33(), $this->get34(), $this->get35());
        return $object;
    }

    protected function get37()
    {
        return $this->delegateContainer->get('AstraChild\\Factories\\JobDataFactory');
    }

    protected function get36()
    {
        $object = new AstraChild\Services\Job\JobServices($this->get37());
        return $object;
    }

    protected function get38()
    {
        $object = new AstraChild\Services\Job\ArchiveServices();
        return $object;
    }

    protected function get39()
    {
        $object = new AstraChild\Layouts\Layouts();
        return $object;
    }

    protected function get41()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\JobRepository');
    }

    protected function get40()
    {
        $object = new AstraChild\Components\JobCarousel($this->get41());
        return $object;
    }

    protected function get42()
    {
        $object = new AstraChild\Components\Hero();
        return $object;
    }

    protected function get44()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\Job\\JobServices');
    }

    protected function get45()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\JobRepository');
    }

    protected function get43()
    {
        $object = new AstraChild\Components\JobGrid($this->get44(), $this->get45());
        return $object;
    }

    protected function get47()
    {
        return $this->delegateContainer->get('AstraChild\\Components\\Hero');
    }

    protected function get48()
    {
        return $this->delegateContainer->get('AstraChild\\Components\\JobGrid');
    }

    protected function get49()
    {
        return $this->delegateContainer->get('AstraChild\\Components\\JobCarousel');
    }

    protected function get50()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\Job\\JobServices');
    }

    protected function get51()
    {
        return $this->delegateContainer->get('AstraChild\\Layouts\\Layouts');
    }

    protected function get46()
    {
        $object = new AstraChild\ViewModels\Page\HomepageViewModel($this->get47(), $this->get48(), $this->get49(), $this->get50(), $this->get51());
        return $object;
    }

    protected function get53()
    {
        return $this->delegateContainer->get('AstraChild\\Components\\Hero');
    }

    protected function get54()
    {
        return $this->delegateContainer->get('AstraChild\\Components\\JobGrid');
    }

    protected function get55()
    {
        return $this->delegateContainer->get('AstraChild\\QueryBuilders\\JobQuery');
    }

    protected function get56()
    {
        return $this->delegateContainer->get('AstraChild\\Layouts\\Layouts');
    }

    protected function get52()
    {
        $object = new AstraChild\ViewModels\Page\ArchiveViewModel($this->get53(), $this->get54(), $this->get55(), $this->get56());
        return $object;
    }

    protected function get58()
    {
        return $this->delegateContainer->get('AstraChild\\ViewModels\\Page\\HomepageViewModel');
    }

    protected function get57()
    {
        $object = new AstraChild\Views\Page\HomepageView($this->get58());
        return $object;
    }

    protected function get60()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\Job\\JobServices');
    }

    protected function get61()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\REST\\RESTData');
    }

    protected function get62()
    {
        return $this->delegateContainer->get('AstraChild\\Layouts\\Layouts');
    }

    protected function get59()
    {
        $object = new AstraChild\Views\Page\SingleView($this->get60(), $this->get61(), $this->get62());
        return $object;
    }

    protected function get64()
    {
        return $this->delegateContainer->get('AstraChild\\ViewModels\\Page\\ArchiveViewModel');
    }

    protected function get63()
    {
        $object = new AstraChild\Views\Page\ArchiveView($this->get64());
        return $object;
    }

    protected function get66()
    {
        return $this->delegateContainer->get('AstraChild\\Layouts\\Layouts');
    }

    protected function get65()
    {
        $object = new AstraChild\Views\Page\PasangIklanView($this->get66());
        return $object;
    }

    protected function get67()
    {
        $object = new AstraChild\Core\Enqueue\Vite();
        return $object;
    }

    protected function get68()
    {
        $object = new AstraChild\Core\Hooks();
        return $object;
    }

    protected function get70()
    {
        return $this->delegateContainer->get('AstraChild\\Core\\Enqueue\\Vite');
    }

    protected function get69()
    {
        $object = new AstraChild\Core\Enqueue($this->get70());
        return $object;
    }

    protected function get71()
    {
        return $this->resolveFactory(static fn($c) =>
                new \AstraChild\Core\Init(
                    [
                        $c->get(\AstraChild\Core\Enqueue::class),
                        $c->get(\AstraChild\Core\Hooks::class),
                        $c->get(\AstraChild\Models\Schema\CustomFields::class),
                        $c->get(\AstraChild\Models\Schema\Taxonomies::class),
                        $c->get(\AstraChild\Models\Schema\PostTypes::class),
                        $c->get(\AstraChild\Services\REST\RESTRoute::class),
                        $c->get(\AstraChild\Services\Job\ArchiveServices::class),
                        $c->get(\AstraChild\Services\Taxonomy\TaxonomyManagement::class),
                        $c->get(\AstraChild\Services\PostsManagement\PostsManagement::class)
                    ],
                ), 'AstraChild\\Core\\Init');
    }

    protected function get72()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\CustomFieldRepository');
    }

    protected function get73()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\TaxonomyRepository');
    }

    protected function get75()
    {
        return $this->delegateContainer->get('customFieldsProvider');
    }

    protected function get76()
    {
        return $this->delegateContainer->get('taxonomiesProvider');
    }

    protected function get77()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\CustomField\\CustomFieldsService');
    }

    protected function get78()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\Taxonomy\\TaxonomyService');
    }

    protected function get74()
    {
        $object = new AstraChild\Factories\JobDataFactory($this->get75(), $this->get76(), $this->get77(), $this->get78());
        return $object;
    }

    protected function get79()
    {
        $object = new AstraChild\QueryBuilders\JobQuery();
        return $object;
    }

}
