<?php
declare(strict_types=1);

namespace WPLokerBJM\Core\Container\Attributes;

use Attribute;

/**
 * Attribute for WordPress actions.
 * 
 * @template TObject of object
 */
#[Attribute(Attribute::TARGET_METHOD | Attribute::TARGET_PROPERTY | Attribute::IS_REPEATABLE)]
class Action
{
    /**
     * Types autocomplete DX generated by generate-meta-hooks.php
     *
     * @param string|\Closure $hook
     * @param int $priority
     * @param int $acceptedArgs
     * @param bool $defer defer activation
     * 
     * @param (\Closure(TObject...): bool)|null $executeIf
     * @param-closure-this $executeIf TObject
     * 
     * @param (\Closure(TObject...): bool)|null $registerIf
     * @param-closure-this $registerIf TObject
     * 
     * @param array<string> $tag
     */
    public function __construct(
        public readonly string|\Closure $hook,
        public readonly int $priority = 10,
        public readonly int $acceptedArgs = 1,
        public readonly bool $defer = false,
        public readonly ?\Closure $executeIf = null,
        public readonly ?\Closure $registerIf = null,
        public readonly array $tag = []
    ) {
    }
}
/**
 * Attribute for WordPress filters.
 * @template TObject of object
 */
#[Attribute(Attribute::TARGET_METHOD | Attribute::TARGET_PROPERTY | Attribute::IS_REPEATABLE)]
class Filter
{
        /**
     * Types autocomplete DX generated by generate-meta-hooks.php
     *
     * @param string|\Closure $hook
     * @param int $priority
     * @param int $acceptedArgs
     * @param bool $defer defer activation
     * 
     * @param (\Closure(TObject...): bool)|null $executeIf
     * @param-closure-this $executeIf TObject
     * 
     * @param (\Closure(TObject...): bool)|null $registerIf
     * @param-closure-this $registerIf TObject
     * 
     * @param array<string> $tag
     */
    public function __construct(
        public readonly string|\Closure $hook,
        public readonly int $priority = 10,
        public readonly int $acceptedArgs = 1,
        public readonly bool $defer = false,
        public readonly ?\Closure $executeIf = null,
        public readonly ?\Closure $registerIf = null,
        public readonly array $tag = []
    ) {
    }
}