<?php
declare(strict_types=1);

namespace WPLokerBJM\Core\Container\Attributes;

use Attribute;

/**
 * Attribute for WordPress actions.
 * 
 * @template TObject of object
 */
#[Attribute(Attribute::TARGET_METHOD | Attribute::TARGET_PROPERTY | Attribute::IS_REPEATABLE)]
class Action
{

    /**
     * Types autocomplete DX generated by generate-meta-hooks.php
     *
     * @param string|\Closure $hook
     * @param int $priority
     * @param int $acceptedArgs
     * @param bool $deferRegister defer activation (forced true when $deferRegisterUntilHook is set)
     * 
     * @param (\Closure(TObject...): bool)|null $executeIf decide whether to execute callback, potentially instantiating the object
     * @param-closure-this $executeIf TObject
     * 
     * @param (\Closure(TObject...): bool)|null $registerIf decide whether to register the hook
     * @param-closure-this $registerIf TObject
     * 
     * @param array<int, string|\BackedEnum|\Closure(TObject...): array> $tag
     * @param-closure-this $tag
     * 
     * @param string|(\Closure(TObject...): string)|null $deferRegisterUntilHook !Unusable with RuntimeRegistry
     * !defer registration until the named 'action' trigger hook fires (implies defer); a Closure is resolved through the container and must return the trigger hook name
     * @param bool $once consume-on-any-evaluation: the registration removes itself after executeIf is evaluated, regardless of whether the gate passed
     */
    public function __construct(
        public readonly string|\Closure $hook,
        public readonly int $priority = 10,
        public readonly int $acceptedArgs = 1,
        public readonly ?\Closure $executeIf = null,
        public readonly ?\Closure $registerIf = null,
        public readonly array|\Closure $tag = [],
        public readonly string|\Closure|null $deferRegisterUntilHook = null,
        public bool $deferRegister = false,
        public readonly bool $once = false,
    ) {
        $this->deferRegister = $deferRegisterUntilHook !== null ? true : $deferRegister;
    }
}
/**
 * Attribute for WordPress filters.
 * @template TObject of object
 */
#[Attribute(Attribute::TARGET_METHOD | Attribute::TARGET_PROPERTY | Attribute::IS_REPEATABLE)]
class Filter
{
    /**
     * Types autocomplete DX generated by generate-meta-hooks.php
     *
     * @param string|\Closure $hook
     * @param int $priority
     * @param int $acceptedArgs
     * @param bool $deferRegister defer activation (forced true when $deferRegisterUntilHook is set)
     * 
     * @param (\Closure(TObject...): bool)|null $executeIf decide whether to execute callback, potentially instantiating the object
     * @param-closure-this $executeIf TObject
     * 
     * @param (\Closure(TObject...): bool)|null $registerIf decide whether to register the hook
     * @param-closure-this $registerIf TObject
     * 
     * @param array<int, string|\BackedEnum|\Closure(TObject...): array> $tag
     * @param-closure-this $tag
     * 
     * @param string|(\Closure(TObject...): string)|null $deferRegisterUntilHook defer registration until the named 'action' trigger hook fires (implies defer); a Closure is resolved through the container and must return the trigger hook name
     * @param bool $once consume-on-any-evaluation: the registration removes itself after executeIf is evaluated, regardless of whether the gate passed
     */
    public function __construct(
        public readonly string|\Closure $hook,
        public readonly int $priority = 10,
        public readonly int $acceptedArgs = 1,
        public readonly ?\Closure $executeIf = null,
        public readonly ?\Closure $registerIf = null,
        public readonly array|\Closure $tag = [],
        public readonly string|\Closure|null $deferRegisterUntilHook = null,
        public bool $deferRegister = false,
        public readonly bool $once = false,
    ) {
        $this->deferRegister = $deferRegisterUntilHook !== null ? true : $deferRegister;
    }
}