<?php
declare(strict_types=1);
namespace WPLokerBJM\Core\Container\Attributes;

use Attribute;


/**
 * Attribute for WordPress actions.
 * Annotate a method to register it as an action hook.
 */
#[Attribute(Attribute::TARGET_METHOD | Attribute::TARGET_PROPERTY | Attribute::IS_REPEATABLE)]
class Action
{
    /**
     ** types autocomplete DX generated by generate-meta-hooks.php
     * @param string $hook
     * @param int $priority
     * @param int $acceptedArgs
     * @param bool $defer defer activation
     * @param \Closure|null $condition Gate the hook: receives Psr\Container\ContainerInterface, must return bool. 
     * Intercept and fire hook only when it returns true, Condition are useful to prevent instantiation of whole class
     * @param array<string> $tag Grouping tag(s) for bulk activation/unregistration.
     */
    public function __construct(
        public readonly string $hook,
        public readonly int $priority = 10,
        public readonly int $acceptedArgs = 1,
        public readonly bool $defer = false,
        public readonly ?\Closure $condition = null,
        public readonly array $tag = []
    ) {
    }
}

/**
 * Attribute for WordPress filters.
 */
#[Attribute(Attribute::TARGET_METHOD | Attribute::TARGET_PROPERTY | Attribute::IS_REPEATABLE)]
class Filter
{
    /**
     ** types autocomplete DX generated by generate-meta-hooks.php
     * @param string $hook
     * @param int $priority
     * @param int $acceptedArgs
     * @param bool $defer defer activation
     * @param \Closure|null $condition Runtime gate the hook: receives Psr\Container\ContainerInterface, must return bool. 
     * Intercept and fire hook only when it returns true, Condition are useful to prevent instantiation of class.
     * @param array<string> $tag Grouping tag(s) for bulk activation/unregistration.
     */
    public function __construct(
        public readonly string $hook,
        public readonly int $priority = 10,
        public readonly int $acceptedArgs = 1,
        public readonly bool $defer = false,
        public readonly ?\Closure $condition = null,
        public readonly array $tag = []
    ) {
    }
}