<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'AstraChild\\Core\\Enqueue' => 'get1',
  'AstraChild\\Core\\Actions' => 'get2',
  'AstraChild\\Core\\Filters' => 'get3',
  'AstraChild\\Core\\Init' => 'get4',
  'subEntry1' => 'get5',
  'subEntry2' => 'get6',
  'subEntry3' => 'get7',
  'subEntry4' => 'get8',
  'subEntry5' => 'get9',
  'subEntry6' => 'get10',
  'subEntry7' => 'get11',
  'subEntry8' => 'get12',
  'subEntry9' => 'get13',
  'subEntry10' => 'get14',
  'AstraChild\\Contracts\\DataProviderInterface' => 'get15',
  'customFieldsProvider' => 'get16',
  'taxonomiesProvider' => 'get17',
  'AstraChild\\Repositories\\JobRepository' => 'get18',
  'subEntry11' => 'get19',
  'AstraChild\\Factories\\JobDataFactory' => 'get20',
  'subEntry12' => 'get21',
  'subEntry13' => 'get22',
  'subEntry14' => 'get23',
  'subEntry15' => 'get24',
  'subEntry16' => 'get25',
  'AstraChild\\ViewModels\\Page\\SingleViewModel' => 'get26',
  'subEntry17' => 'get27',
  'subEntry18' => 'get28',
  'subEntry19' => 'get29',
  'subEntry20' => 'get30',
  'subEntry21' => 'get31',
  'AstraChild\\ViewModels\\Page\\HomepageViewModel' => 'get32',
  'AstraChild\\ViewModels\\Page\\ArchiveViewModel' => 'get33',
  'AstraChild\\ViewModels\\Page\\PasangIklanViewModel' => 'get34',
  'AstraChild\\Services\\CustomField\\CustomFieldsService' => 'get35',
  'AstraChild\\Services\\Taxonomy\\TaxonomyService' => 'get36',
  'AstraChild\\Services\\CustomField\\SocialMediaService' => 'get37',
  'AstraChild\\Services\\REST\\RESTServices' => 'get38',
  'AstraChild\\Services\\Job\\JobServices' => 'get39',
  'subEntry22' => 'get40',
  'subEntry23' => 'get41',
  'subEntry24' => 'get42',
  'AstraChild\\Services\\Job\\ArchiveServices' => 'get43',
  'AstraChild\\Services\\PostsManagement\\PostsManagement' => 'get44',
  'AstraChild\\Views\\Page\\SingleView' => 'get45',
  'subEntry25' => 'get46',
  'AstraChild\\Views\\Page\\HomepageView' => 'get47',
  'subEntry26' => 'get48',
  'AstraChild\\Views\\Page\\ArchiveView' => 'get49',
  'subEntry27' => 'get50',
  'AstraChild\\Views\\Page\\PasangIklanView' => 'get51',
  'subEntry28' => 'get52',
  'AstraChild\\Models\\Schema\\CustomFields' => 'get53',
  'AstraChild\\Models\\Schema\\Taxonomies' => 'get54',
  'AstraChild\\Models\\Schema\\PostTypes' => 'get55',
  'AstraChild\\Repositories\\CustomFieldRepository' => 'get56',
  'AstraChild\\Repositories\\TaxonomyRepository' => 'get57',
  'AstraChild\\Services\\Job\\FormatterServices' => 'get58',
);

    protected function get1()
    {
        $object = new AstraChild\Core\Enqueue();
        return $object;
    }

    protected function get2()
    {
        $object = new AstraChild\Core\Actions();
        return $object;
    }

    protected function get3()
    {
        $object = new AstraChild\Core\Filters();
        return $object;
    }

    protected function get6()
    {
        return $this->delegateContainer->get('AstraChild\\Core\\Enqueue');
    }

    protected function get7()
    {
        return $this->delegateContainer->get('AstraChild\\Core\\Actions');
    }

    protected function get8()
    {
        return $this->delegateContainer->get('AstraChild\\Core\\Filters');
    }

    protected function get9()
    {
        return $this->delegateContainer->get('AstraChild\\Models\\Schema\\CustomFields');
    }

    protected function get10()
    {
        return $this->delegateContainer->get('AstraChild\\Models\\Schema\\Taxonomies');
    }

    protected function get11()
    {
        return $this->delegateContainer->get('AstraChild\\Models\\Schema\\PostTypes');
    }

    protected function get12()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\REST\\RESTServices');
    }

    protected function get13()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\Job\\ArchiveServices');
    }

    protected function get14()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\PostsManagement\\PostsManagement');
    }

    protected function get5()
    {
        return [
            0 => $this->get6(),
            1 => $this->get7(),
            2 => $this->get8(),
            3 => $this->get9(),
            4 => $this->get10(),
            5 => $this->get11(),
            6 => $this->get12(),
            7 => $this->get13(),
            8 => $this->get14(),
        ];
    }

    protected function get4()
    {
        $object = new AstraChild\Core\Init($this->get5());
        return $object;
    }

    protected function get15()
    {
        return $this->resolveFactory(static function() {
                return new \AstraChild\Repositories\CustomFieldRepository();
            }, 'AstraChild\\Contracts\\DataProviderInterface');
    }

    protected function get16()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\CustomFieldRepository');
    }

    protected function get17()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\TaxonomyRepository');
    }

    protected function get19()
    {
        return $this->delegateContainer->get('AstraChild\\Factories\\JobDataFactory');
    }

    protected function get18()
    {
        $object = new AstraChild\Repositories\JobRepository($this->get19());
        return $object;
    }

    protected function get21()
    {
        return $this->delegateContainer->get('customFieldsProvider');
    }

    protected function get22()
    {
        return $this->delegateContainer->get('taxonomiesProvider');
    }

    protected function get23()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\CustomField\\CustomFieldsService');
    }

    protected function get24()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\Taxonomy\\TaxonomyService');
    }

    protected function get25()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\CustomField\\SocialMediaService');
    }

    protected function get20()
    {
        $object = new AstraChild\Factories\JobDataFactory($this->get21(), $this->get22(), $this->get23(), $this->get24(), $this->get25());
        return $object;
    }

    protected function get27()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\JobRepository');
    }

    protected function get28()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\CustomField\\SocialMediaService');
    }

    protected function get29()
    {
        return $this->delegateContainer->get('AstraChild\\Factories\\JobDataFactory');
    }

    protected function get30()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\Job\\FormatterServices');
    }

    protected function get31()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\Job\\JobServices');
    }

    protected function get26()
    {
        $object = new AstraChild\ViewModels\Page\SingleViewModel($this->get27(), $this->get28(), $this->get29(), $this->get30(), $this->get31());
        return $object;
    }

    protected function get32()
    {
        $object = new AstraChild\ViewModels\Page\HomepageViewModel();
        return $object;
    }

    protected function get33()
    {
        $object = new AstraChild\ViewModels\Page\ArchiveViewModel();
        return $object;
    }

    protected function get34()
    {
        $object = new AstraChild\ViewModels\Page\PasangIklanViewModel();
        return $object;
    }

    protected function get35()
    {
        $object = new AstraChild\Services\CustomField\CustomFieldsService();
        return $object;
    }

    protected function get36()
    {
        $object = new AstraChild\Services\Taxonomy\TaxonomyService();
        return $object;
    }

    protected function get37()
    {
        $object = new AstraChild\Services\CustomField\SocialMediaService();
        return $object;
    }

    protected function get38()
    {
        $object = new AstraChild\Services\REST\RESTServices();
        return $object;
    }

    protected function get40()
    {
        return $this->delegateContainer->get('AstraChild\\Repositories\\JobRepository');
    }

    protected function get41()
    {
        return $this->delegateContainer->get('AstraChild\\Factories\\JobDataFactory');
    }

    protected function get42()
    {
        return $this->delegateContainer->get('AstraChild\\Services\\CustomField\\SocialMediaService');
    }

    protected function get39()
    {
        $object = new AstraChild\Services\Job\JobServices($this->get40(), $this->get41(), $this->get42());
        return $object;
    }

    protected function get43()
    {
        $object = new AstraChild\Services\Job\ArchiveServices();
        return $object;
    }

    protected function get44()
    {
        $object = new AstraChild\Services\PostsManagement\PostsManagement();
        return $object;
    }

    protected function get46()
    {
        return $this->delegateContainer->get('AstraChild\\ViewModels\\Page\\SingleViewModel');
    }

    protected function get45()
    {
        $object = new AstraChild\Views\Page\SingleView($this->get46());
        return $object;
    }

    protected function get48()
    {
        return $this->delegateContainer->get('AstraChild\\ViewModels\\Page\\HomepageViewModel');
    }

    protected function get47()
    {
        $object = new AstraChild\Views\Page\HomepageView($this->get48());
        return $object;
    }

    protected function get50()
    {
        return $this->delegateContainer->get('AstraChild\\ViewModels\\Page\\ArchiveViewModel');
    }

    protected function get49()
    {
        $object = new AstraChild\Views\Page\ArchiveView($this->get50());
        return $object;
    }

    protected function get52()
    {
        return $this->delegateContainer->get('AstraChild\\ViewModels\\Page\\PasangIklanViewModel');
    }

    protected function get51()
    {
        $object = new AstraChild\Views\Page\PasangIklanView($this->get52());
        return $object;
    }

    protected function get53()
    {
        $object = new AstraChild\Models\Schema\CustomFields();
        return $object;
    }

    protected function get54()
    {
        $object = new AstraChild\Models\Schema\Taxonomies();
        return $object;
    }

    protected function get55()
    {
        $object = new AstraChild\Models\Schema\PostTypes();
        return $object;
    }

    protected function get56()
    {
        $object = new AstraChild\Repositories\CustomFieldRepository();
        return $object;
    }

    protected function get57()
    {
        $object = new AstraChild\Repositories\TaxonomyRepository();
        return $object;
    }

    protected function get58()
    {
        $object = new AstraChild\Services\Job\FormatterServices();
        return $object;
    }

}
