<?php

declare(strict_types=1);
namespace WPLokerBJM\Core\Container\Support\WPHooks;

use HookTargetResolve;
use ReflectionClass;
use DI\Container;
use WPLokerBJM\Shared\Log\Logger;
use Psr\Container\ContainerInterface;
use WPLokerBJM\Core\Container\Support\WPHooks\Abstract\{AnonClassHookPropertyAbstract};
use WPLokerBJM\Core\Container\Attributes\{Action, Filter};
use WPLokerBJM\Core\Container\Support\WPHooks\Trait\HookScannerTrait;

/**
 * Registry for WordPress hooks discovered via #[Action] and #[Filter] attributes.
 *
 * Stores all hook registrations as identifiable LazyHookHandler instances,
 * enabling unregistration by hook name, class, or specific class::method.
 * Service resolution is deferred to hook-fire time (lazy loading).
 *
 * @phpstan-import-type HookRegistration from WPHooksScanner
 *
 * @phpstan-type HandlerEntry array{handler: LazyHookHandler|LazyPropertyHookHandler, type: 'action'|'filter', priority: int, accepted_args: int}
 * @phpstan-type RemoveHandlerEntry array{handler: LazyHookHandler|LazyPropertyHookHandler, type: 'action'|'filter', priority: int}
 * @template TargetClass of Object
 * @phpstan-type HookTargetResolve object<TargetClass>|callable|string|array{object<TargetClass>, string}
 */
class WPHooksRegistry
{
    /**
     * @var array<string, array<string, HandlerEntry>>
     */
    private array $handlers = [];

    /**
     * Deferred handlers not yet registered with WordPress.
     *
     * @var array<string, array<string, HandlerEntry>>
     */
    private array $deferredHandlers = [];

    private bool $initialized = false;

    /**
     * Summary of __construct
     * @param ContainerInterface $container
     * @param HookRegistration[] $hooksRegistration
     */
    public function __construct(
        private readonly ContainerInterface $container,
        private array $hooksRegistration,
    ) {
    }

    /**
     * Register all stored hooks with WordPress via add_action/add_filter.
     */
    public function initialize(): void
    {
        if ($this->initialized) {
            return;
        }
        $this->registerAll($this->hooksRegistration);
        foreach ($this->handlers as $hook => $hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                try {
                    $this->addSingleHook($hook, $data);
                } catch (\Exception $e) {
                    Logger::error(
                        'WPHooksRegistry',
                        "Error registering {$data['type']} '{$hook}' for {$key}: {$e->getMessage()}"
                    );
                }
            }
        }

        $this->initialized = true;
    }

    #region deferred handlers activation methods

    /**
     * Activate all deferred handlers registered for a specific WordPress hook.
     *
     * Moves matching LazyHookHandler instances from $this->deferredHandlers
     * into $this->handlers and registers them with WordPress via add_action/add_filter.
     * Handlers that have already been activated are silently skipped.
     *
     * **Example:**
     * ```php
     * $registry->activateDeferredByHook('init');
     * ```
     ** types autocomplete DX generated by generate-meta-hooks.php
     * @param string $hook WordPress hook name.
     */
    public function activateDeferredByHook(string $hook): void
    {
        if (empty($this->deferredHandlers[$hook])) {
            return;
        }

        foreach ($this->deferredHandlers[$hook] as $key => $data) {
            // Guard: skip if already activated
            if (isset($this->handlers[$hook][$key])) {
                continue;
            }

            $this->handlers[$hook][$key] = $data;

            $this->addSingleHook($hook, $data);
        }

        unset($this->deferredHandlers[$hook]);
    }

    /**
     * Activate all deferred handlers belonging to a specific service class.
     *
     * Scans all deferred hooks and activates any LazyHookHandler whose owning
     * class matches the given FQCN. Already-active handlers are silently skipped.
     *
     * **Example:**
     * ```php
     * $registry->activateDeferredByClass(WPGraphQL::class);
     * ```
     *
     * @param class-string $class Fully qualified class name.
     */
    public function activateDeferredByClass(string $class): void
    {
        $prefix = $class . '::';
        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!str_starts_with($key, $prefix)) {
                    continue;
                }

                // Guard: skip if already activated
                if (isset($this->handlers[$hook][$key])) {
                    unset($hookHandlers[$key]);
                    continue;
                }

                $this->handlers[$hook][$key] = $data;

                $this->addSingleHook($hook, $data);

                unset($hookHandlers[$key]);
            }
            if (empty($hookHandlers)) {
                unset($this->deferredHandlers[$hook]);
            }
        }
        unset($hookHandlers);
    }

    /**
     * Activate deferred hook handlers matching the specified target callable or identifier.
     *
     * Scans the deferred handlers pool and transfers matching entries to the active pool,
     * registering them immediately with WordPress via `add_action()` or `add_filter()`.
     * Works seamlessly across standard instance methods, first-class callables, PHP 8.4
     * property hooks, array targets, and class-string identifiers.
     *
     * Already-activated handlers are silently skipped to prevent duplicate registrations.
     *
     * **Usage Examples:**
     *
     ** 1. First-Class Callable (Recommended for External Orchestrators):
     * Provides full IDE autocompletion, type safety, and static refactoring support.
     * ```php
     *! $registry->activateDeferredByCallable($this->graphQL->setCacheHeader(...));
     * ```
     *
     ** 2. Self-Referencing Array (Recommended for Internal Method Self-Activation):
     * Fast-path resolution when a method manages its own hook status. DRY and refactor-proof via `__FUNCTION__`.
     * ```php
     *! $registry->activateDeferredByCallable([$this, __FUNCTION__]);
     * ```
     *
     ** 3. String Identifier (Class::method):**
     * Useful for static activation or when an active instance reference is not readily available.
     * ```php
     *! $registry->activateDeferredByCallable(GraphQLService::class . '::setCacheHeader');
     * ```
     *
     ** 4. Array Lookup (`[$object, 'method']`):**
     * Traditional PHP callable array syntax for instance method target resolution.
     * ```php
     *! $registry->activateDeferredByCallable([$this->graphQL, 'setCacheHeader']);
     * ```
     *
     ** 5. PHP 8.4 Property Hooks & Dynamic Invokables:**
     * Activates closures or invokable objects held within class properties.
     * On property: 
     * ```php
     * private $disableNoCacheHeaders = static function() { return false; };
     *
     *! $registry->activateDeferredByCallable($this->graphQL->disableNoCacheHeaders);
     * ```
     *
     * @param HookTargetResolve $target First-class callable, array `[$object, 'method']`,
     *                                  string `'Class::method'`, or invokable property reference.
     *
     * @return void
     * @throws \InvalidArgumentException If the target cannot be resolved to a valid class and member.
     */
    public function activateDeferredByCallable(callable|string|array $target): void
    {
        [$class, $method] = ($this->resolverTarget)($target);
        $prefix = $class . '::' . $method . '::';
        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!str_starts_with($key, $prefix)) {
                    continue;
                }

                if (isset($this->handlers[$hook][$key])) {
                    unset($hookHandlers[$key]);
                    continue;
                }

                $this->handlers[$hook][$key] = $data;
                $this->addSingleHook($hook, $data);
                unset($hookHandlers[$key]);
            }
            if (empty($hookHandlers)) {
                unset($this->deferredHandlers[$hook]);
            }
        }
        unset($hookHandlers);
    }
    #endregion

    #region deferred handlers unregisteration methods
    /**
     * Unregister a deferred hook using a first-class callable, array lookup,
     * or class-string identifier.
     *
     * @param HookTargetResolve $target
     */
    public function unregisterDeferredByCallable(callable|string|array $target): void
    {
        [$class, $method] = ($this->resolverTarget)($target);
        $prefix = $class . '::' . $method . '::';

        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach (array_keys($hookHandlers) as $key) {
                if (str_starts_with($key, $prefix)) {
                    unset($hookHandlers[$key]);
                }
            }
        }
    }

    /**
     * Unregister all deferred handlers for a specific WordPress hook name.
     *
     * @param string $hook WordPress hook name.
     */
    public function unregisterDeferredByHook(string $hook): void
    {
        unset($this->deferredHandlers[$hook]);
    }

    /**
     * Unregister all deferred hooks belonging to a specific service class.
     *
     * @param class-string $class Fully qualified class name.
     */
    public function unregisterDeferredByClass(string $class): void
    {
        $prefix = $class . '::';
        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $_) {
                if (str_starts_with($key, $prefix)) {
                    unset($hookHandlers[$key]);
                }
            }
        }
    }
    #endregion
    #region main handlers unregisteration methods
    /**
     * Unregister a registered hook via first-class callable, array lookup,
     * or class-string identifier.
     *
     * @param HookTargetResolve $target
     */
    public function unregisterByCallable(callable|string|array $target): void
    {
        [$class, $method] = ($this->resolverTarget)($target);
        $prefix = $class . '::' . $method . '::';

        foreach ($this->handlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!str_starts_with($key, $prefix)) {
                    continue;
                }
                $this->removeSingleHook($hook, $data);
                unset($hookHandlers[$key]);
            }
        }
        unset($hookHandlers);
    }

    /**
     * Unregister all handlers for a specific WordPress hook name.
     *
     * @param string $hook WordPress hook name.
     */
    public function unregisterByHook(string $hook): void
    {
        foreach ($this->handlers[$hook] ?? [] as $data) {
            $this->removeSingleHook($hook, $data);
        }

        unset($this->handlers[$hook]);
    }

    /**
     * Unregister all hooks belonging to a specific service class.
     *
     * @param class-string $class Fully qualified class name.
     */
    public function unregisterByClass(string $class): void
    {
        $prefix = $class . '::';
        foreach ($this->handlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!str_starts_with($key, $prefix)) {
                    continue;
                }
                $this->removeSingleHook($hook, $data);
                unset($hookHandlers[$key]);
            }
        }
        unset($hookHandlers);
    }
    #endregion

    #region Resolver Target Logics
    /**
     * Lazily-created callable target resolver.
     *
     * Implemented as an anonymous invokable object so it can serve as
     * demonstration of invokable object(class) and encapsulate per-request state
     * Resolves supported hook targets:
     *  - first-class callables
     *  - [$object, 'method']
     *  - 'Class::method'
     *  - invokable objects
     *  - PHP 8.4 property hook closures
     *
     * @return callable(HookTargetResolve): array{class-string, string}
     */
    private $resolverTarget {
        get => $this->resolverTarget ??= new class () {
            /**
             * Per-request cache of resolved callable → [FQCN, memberName].
             *
             * WeakMap automatically drops entries when their key (the callable
             * object) is garbage-collected, avoiding memory leaks.
             *
             * @var \WeakMap<object, array{class-string, string}>
             */
            private \WeakMap $callableTargetCache;

            public function __construct()
            {
                $this->callableTargetCache = new \WeakMap();
            }

            /**
             * @param HookTargetResolve $target
             * @return array{class-string, string}
             */
            public function __invoke(object|callable|array|string $target): array
            {
                if (is_object($target) && isset($this->callableTargetCache[$target])) {
                    return $this->callableTargetCache[$target];
                }

                $result = $this->doResolveCallableTarget($target);

                if (is_object($target)) {
                    $this->callableTargetCache[$target] = $result;
                }
                return $result;
            }
            /**
             * @param HookTargetResolve $target
             * @return array{class-string, string}
             */
            private function doResolveCallableTarget(object|callable|array|string $target): array
            {
                // 1. Array [$object, 'memberName'] — fast path
                if (is_array($target)) {
                    return [get_class($target[0]), $target[1]];
                }

                // 2. String 'Class::method' — static fallback
                if (is_string($target)) {
                    $parts = explode('::', $target, 2);
                    return [$parts[0], $parts[1] ?? '__invoke'];
                }

                // 3. Invokable Object Instance (anonymous class from a property)
                if (!$target instanceof \Closure && is_object($target)) {
                    return $this->analyseObject($target);
                }

                // 4. Closure (First-class callable or PHP 8.4 property hook accessor)
                $ref = new \ReflectionFunction($target);
                $calledClass = $ref->getClosureCalledClass()?->getName();

                if ($calledClass === null) {
                    throw new \InvalidArgumentException('Callable target must be bound to an object instance.');
                }

                $name = $ref->getName();

                // Standard Instance Method ($service->method(...))
                if (!str_contains($name, '{closure')) {
                    return [$calledClass, $name];
                }

                // PHP 8.4 Property Hook Closure ("{closure:FQCN::$propertyName::get():line}")
                if (str_contains($name, '::$')) {
                    $start = strpos($name, '::$') + 3;
                    $end = strpos($name, '::', $start);

                    if ($start !== false && $end !== false) {
                        return [$calledClass, substr($name, $start, $end - $start)];
                    }
                }

                throw new \InvalidArgumentException("Unable to resolve hook target for class {$calledClass}.");
            }

            /**
             * 
             * @param object $target
             * @return array{class-string, string}
             */
            private function analyseObject(object $target): array
            {
                $className = $target::class;

                // Anonymous class extending AnonClassHookPropertyAbstract —
                // reads parent class & property directly, no backtrace needed.
                if ($target instanceof AnonClassHookPropertyAbstract) {
                    return [$target->parentClass, $target->parentProperty];
                }

                // Best-effort fallback for anonymous classes that don't
                // extend the AnonClassHookPropertyAbstract: walk the call stack to find which
                // object's property holds this instance.
                if ((new ReflectionClass($target))->isAnonymous()) {
                    $backtrace = debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT, 10);
                    foreach ($backtrace as $frame) {
                        $callerObject = $frame['object'] ?? null;
                        if ($callerObject === null) {
                            continue;
                        }
                        $refClass = new ReflectionClass($callerObject);
                        foreach ($refClass->getProperties() as $property) {
                            if ($property->isInitialized($callerObject) && $property->getValue($callerObject) === $target) {
                                Logger::warning("WPHooksRegistry: ", "Anon class without extending AnonClassHookPropertyAbstract, it's recommended to use 'AnonClassHookPropertyAbstract'." . $refClass->getName() . "::" . $property->getName());
                                return [$refClass->getName(), $property->getName()];
                            }
                        }
                    }
                }

                return [$className, '__invoke'];
            }
        };
    }

    #endregion
    /**
     * Internal: call add_action or add_filter for a single handler entry.
     *
     * @param string $hook
     * @param HandlerEntry $data
     */
    private function addSingleHook(string $hook, array $data): void
    {
        if ($data['type'] === 'action') {
            add_action($hook, $data['handler'], $data['priority'], $data['accepted_args']);
        } else {
            add_filter($hook, $data['handler'], $data['priority'], $data['accepted_args']);
        }
    }

    /**
     * Internal: call remove_action or remove_filter for a single handler entry.
     *
     * @param RemoveHandlerEntry $data
     */
    private function removeSingleHook(string $hook, array $data): void
    {
        if ($data['type'] === 'action') {
            remove_action($hook, $data['handler'], $data['priority']);
        } else {
            remove_filter($hook, $data['handler'], $data['priority']);
        }
    }

    /**
     * Register hook registrations from the scanner.
     * Pre-builds LazyHookHandler instances and validates container existence.
     *
     * @param HookRegistration[] $registrations
     */
    private function registerAll(array $registrations): void
    {
        foreach ($registrations as $reg) {
            if (!$this->container->has($reg['class'])) {
                Logger::warning(
                    'WPHooksRegistry',
                    'Skipping hook ' . $reg['hook']
                    . ' — class not in container: ' . $reg['class']
                );
                continue;
            }

            $visibility = $reg['visibility'] ?? 'public';
            $handler = ($reg['target'] ?? 'method') === 'method'
                ? new LazyHookHandler($this->container, $reg['class'], $reg['method'], $visibility, $reg['type'])
                : new LazyPropertyHookHandler($this->container, $reg['class'], $reg['method'], $visibility, $reg['type']);

            $key = $reg['class'] . '::' . $reg['method'] . '::' . $reg['target'] . '::' . $reg['type'] . '::' . $reg['priority'] . '::' . $reg['accepted_args'];
            $target = !empty($reg['defer'])
                ? 'deferredHandlers'
                : 'handlers';
            $this->{$target}[$reg['hook']][$key] = [
                'handler' => $handler,
                'type' => $reg['type'],
                'priority' => $reg['priority'],
                'accepted_args' => $reg['accepted_args'],
            ];
        }
    }
}

/**
 * Runtime hook registry for on-the-fly object hook registration.
 *
 * Unlike WPHooksRegistry (which works with file-scanned, container-resolved
 * classes), this registry registers hooks immediately from an already-
 * instantiated object. This enables hook registration for anonymous classes
 * and dynamically-created objects that cannot be discovered by the file-based
 * WPHooksScanner.
 *
 * Usage:
 *   $service = new class($this->registry) {
 *       #[Action(hook: 'init')]
 *       public function __construct(WPHooksRuntimeRegistry $registry) { 
 *           $registry->registerHooksOn($this); // register
 *           $registry->unregisterHooksOn($this); // unregister (optional)
 *       }
 *       public function onInit(): void { ... }
 *   };
 *
 * All hooks are registered eagerly — the `defer` flag is ignored, and
 * static methods are silently skipped.
 */
class WPHooksRuntimeRegistry
{
    use HookScannerTrait;

    /**
     * Maps registered instances directly to their registered hook metadata and handlers.
     *
     * @var \WeakMap<object, list<array{
     *     handler: RuntimeInstanceHookHandler|RuntimeInstancePropertyHookHandler,
     *     hook: string,
     *     priority: int,
     *     type: 'action'|'filter'
     * }>>
     */
    private \WeakMap $registry;

    public function __construct()
    {
        $this->registry = new \WeakMap();
    }

    /**
     * Scan and register hooks on the given object instance.
     *
     * Non-static methods and properties annotated with #[Action] or
     * #[Filter] are registered via add_action() / add_filter()
     * immediately. Calling this on an already-registered instance is
     * a no-op.
     *
     * @param object $instance An instantiated object with hook-annotated methods/properties.
     */
    public function registerHooksOn(object $instance): void
    {
        // Double-registration guard
        if (isset($this->registry[$instance])) {
            return;
        }

        $records = [];
        $ref = new ReflectionClass($instance);

        $this->scanMethodHooks(
            $ref,
            function (\ReflectionMethod $method, Action|Filter $attr, string $visibility, string $type) use ($instance, &$records): void {
                $handler = new RuntimeInstanceHookHandler(
                    $instance,
                    $method->getName(),
                    $visibility,
                    $type
                );

                if ($type === 'action') {
                    \add_action($attr->hook, $handler, $attr->priority, $attr->acceptedArgs);
                } else {
                    \add_filter($attr->hook, $handler, $attr->priority, $attr->acceptedArgs);
                }

                $records[] = [
                    'handler'  => $handler,
                    'hook'     => $attr->hook,
                    'priority' => $attr->priority,
                    'type'     => $type,
                ];
            }
        );

        $this->scanPropertyHooks(
            $ref,
            function (\ReflectionProperty $property, Action|Filter $attr, string $visibility, string $type, string $target) use ($instance, &$records): void {
                $handler = new RuntimeInstancePropertyHookHandler(
                    $instance,
                    $property->getName(),
                    $visibility,
                    $type
                );

                if ($type === 'action') {
                    \add_action($attr->hook, $handler, $attr->priority, $attr->acceptedArgs);
                } else {
                    \add_filter($attr->hook, $handler, $attr->priority, $attr->acceptedArgs);
                }

                $records[] = [
                    'handler'  => $handler,
                    'hook'     => $attr->hook,
                    'priority' => $attr->priority,
                    'type'     => $type,
                ];
            }
        );

        $this->registry[$instance] = $records;
    }

    /**
     * Remove all hooks previously registered for the given instance.
     *
     * Calls remove_action() / remove_filter() for each registered hook
     * and clears internal tracking. Calling this on an instance that was
     * never registered is a no-op.
     *
     * @param object $instance The instance whose hooks should be removed.
     */
    public function unregisterHooksOn(object $instance): void
    {
        if (!isset($this->registry[$instance])) {
            return;
        }

        foreach ($this->registry[$instance] as $record) {
            if ($record['type'] === 'action') {
                \remove_action($record['hook'], $record['handler'], $record['priority']);
            } else {
                \remove_filter($record['hook'], $record['handler'], $record['priority']);
            }
        }

        unset($this->registry[$instance]);
    }
}