<?php

namespace WPLokerBJM\Core\Container\Support\WPHooks;

use Psr\Container\ContainerInterface;
use ReflectionClass;
use ReflectionMethod;
use ReflectionProperty;
use WPLokerBJM\Core\Container\Attributes\{Action, Filter};
use WPLokerBJM\Bootstrap;
use WPLokerBJM\Shared\Log\Logger;

/**
 * Registry for WordPress hooks discovered via #[Action] and #[Filter] attributes.
 *
 * Stores all hook registrations as identifiable LazyHookHandler instances,
 * enabling unregistration by hook name, class, or specific class::method.
 * Service resolution is deferred to hook-fire time (lazy loading).
 *
 * @phpstan-import-type HookRegistration from WPHooksScanner
 *
 * @phpstan-type HandlerEntry array{handler: LazyHookHandler|LazyPropertyHookHandler, type: 'action'|'filter', priority: int, accepted_args: int}
 * @phpstan-type RemoveHandlerEntry array{handler: LazyHookHandler|LazyPropertyHookHandler, type: 'action'|'filter', priority: int}
 */
class WPHooksRegistry
{
    /**
     * @var array<string, array<string, HandlerEntry>>
     */
    private array $handlers = [];

    /**
     * Deferred handlers not yet registered with WordPress.
     *
     * @var array<string, array<string, HandlerEntry>>
     */
    private array $deferredHandlers = [];

    private bool $initialized = false;

    /**
     * Summary of __construct
     * @param ContainerInterface $container
     * @param HookRegistration[] $hooksRegistration
     */
    public function __construct(
        private readonly ContainerInterface $container,
        private array $hooksRegistration,
    ) {
    }

    /**
     * Register hook registrations from the scanner.
     * Pre-builds LazyHookHandler instances and validates container existence.
     *
     * @param HookRegistration[] $registrations
     */
    private function registerAll(array $registrations): void
    {
        foreach ($registrations as $reg) {
            if (!$this->container->has($reg['class'])) {
                Logger::warning(
                    'WPHooksRegistry',
                    'Skipping hook ' . $reg['hook']
                    . ' — class not in container: ' . $reg['class']
                );
                continue;
            }

            $visibility = $reg['visibility'] ?? 'public';
            $handler = ($reg['target'] ?? 'method') === 'method'
                ? new LazyHookHandler($this->container, $reg['class'], $reg['method'], $visibility, $reg['type'])
                : new LazyPropertyHookHandler($this->container, $reg['class'], $reg['method'], $visibility, $reg['type']);

            $key = $reg['class'] . '::' . $reg['method'] . '::' . $reg['type'] . '::' . $reg['priority'];
            $target = !empty($reg['defer'])
                ? 'deferredHandlers'
                : 'handlers';
            $this->{$target}[$reg['hook']][$key] = [
                'handler' => $handler,
                'type' => $reg['type'],
                'priority' => $reg['priority'],
                'accepted_args' => $reg['accepted_args'],
            ];
        }
    }

    /**
     * Register all stored hooks with WordPress via add_action/add_filter.
     */
    public function initialize(): void
    {
        if ($this->initialized) {
            return;
        }
        $this->registerAll($this->hooksRegistration);
        foreach ($this->handlers as $hook => $hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                try {
                    $this->addSingleHook($hook, $data);
                } catch (\Exception $e) {
                    Logger::error(
                        'WPHooksRegistry',
                        "Error registering {$data['type']} '{$hook}' for {$key}: {$e->getMessage()}"
                    );
                }
            }
        }

        $this->initialized = true;
    }

    /**
     * Activate all deferred handlers registered for a specific WordPress hook.
     *
     * Moves matching LazyHookHandler instances from $this->deferredHandlers
     * into $this->handlers and registers them with WordPress via add_action/add_filter.
     * Handlers that have already been activated are silently skipped.
     *
     * **Example:**
     * ```php
     * $registry->activateDeferredByHook('init');
     * ```
     ** types autocomplete DX generated by generate-meta-hooks.php
     * @param string $hook WordPress hook name.
     */
    public function activateDeferredByHook(string $hook): void
    {
        if (empty($this->deferredHandlers[$hook])) {
            return;
        }

        foreach ($this->deferredHandlers[$hook] as $key => $data) {
            // Guard: skip if already activated
            if (isset($this->handlers[$hook][$key])) {
                continue;
            }

            $this->handlers[$hook][$key] = $data;

            $this->addSingleHook($hook, $data);
        }

        unset($this->deferredHandlers[$hook]);
    }

    /**
     * Activate all deferred handlers belonging to a specific service class.
     *
     * Scans all deferred hooks and activates any LazyHookHandler whose owning
     * class matches the given FQCN. Already-active handlers are silently skipped.
     *
     * **Example:**
     * ```php
     * $registry->activateDeferredByClass(WPGraphQL::class);
     * ```
     *
     * @template T of Object
     * @param class-string<T> $class Fully qualified class name.
     */
    public function activateDeferredByClass(string $class): void
    {
        $prefix = $class . '::';
        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!str_starts_with($key, $prefix)) {
                    continue;
                }

                // Guard: skip if already activated
                if (isset($this->handlers[$hook][$key])) {
                    unset($hookHandlers[$key]);
                    continue;
                }

                $this->handlers[$hook][$key] = $data;

                $this->addSingleHook($hook, $data);

                unset($hookHandlers[$key]);
            }
            if (empty($hookHandlers)) {
                unset($this->deferredHandlers[$hook]);
            }
        }
        unset($hookHandlers);
    }

    /**
     * Activate a specific deferred hook method or property on a service class.
     *
     * Targets a single member (method or public property closure) — the most
     * granular activation.  Already-active handlers are silently skipped.
     *
     * **Examples:**
     *
     * *Activate a **method**-based hook:
     * ```php
     * $registry->activateDeferredByMethod(WPGraphQL::class, 'setCacheHeader');
     * ```
     *
     * *Activate a **property closure** hook — given this class:
     * ```php
     * class WPGraphQL {
     *     #[Filter('graphql_send_nocache_headers', defer: true)]
     *     public $disableNoCacheHeaders = static function (): bool {
     *         return false;
     *     };
     * }
     * ```
     * 
     * Call:
     * ```php
     * $registry->activateDeferredByMethod(WPGraphQL::class, 'disableNoCacheHeaders');
     * ```
     *
     * @template T of Object
     * @param class-string<T> $class  Fully qualified class name.
     * @param key-of<T, string> $method Method or public property name to activate.
     */
    public function activateDeferredByMethod(string $class, string $method): void
    {
        $prefix = $class . '::' . $method . '::';
        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!str_starts_with($key, $prefix)) {
                    continue;
                }

                // Guard: skip if already activated
                if (isset($this->handlers[$hook][$key])) {
                    unset($hookHandlers[$key]);
                    continue;
                }

                $this->handlers[$hook][$key] = $data;

                $this->addSingleHook($hook, $data);

                unset($hookHandlers[$key]);
            }
            if (empty($hookHandlers)) {
                unset($this->deferredHandlers[$hook]);
            }
        }
        unset($hookHandlers);
    }

    /**
     * Unregister all deferred handlers for a specific WordPress hook name.
     *
     * Removes deferred LazyHookHandler instances that were never registered
     * with WordPress — no remove_action/remove_filter needed.
     *
     ** types autocomplete DX generated by generate-meta-hooks.php
     * @param string $hook WordPress hook name (e.g. 'init', 'save_post', 'wp_robots').
     */
    public function unregisterDeferredByHook(string $hook): void
    {
        unset($this->deferredHandlers[$hook]);
    }

    /**
     * Unregister all deferred hooks belonging to a specific service class.
     *
     * Scans deferred handlers and removes every LazyHookHandler whose
     * owning class matches the given FQCN. Since these handlers were
     * never registered with WordPress, no remove_action/remove_filter
     * calls are needed — just internal cleanup.
     *
     * **Example:**
     * ```php
     * $registry->unregisterDeferredByClass(Cloudflare::class);
     * ```
     *
     * @param class-string $class Fully qualified class name.
     */
    public function unregisterDeferredByClass(string $class): void
    {
        $prefix = $class . '::';
        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $_) {
                if (str_starts_with($key, $prefix)) {
                    unset($hookHandlers[$key]);
                }
            }
        }
    }

    /**
     * Unregister a specific deferred hook method or property on a service class.
     *
     * Targets a single member (method or public property closure) — cleanly
     * removes deferred registrations before they're ever registered with
     * WordPress.
     *
     * **Examples:**
     *
     * *Method-based:
     * ```php
     * $registry->unregisterDeferredByMethod(Cloudflare::class, 'purgeCache');
     * ```
     *
     * *Property closure example:
     * ```php
     * #[Action('shutdown', defer: true)] 
     * public $purgeCache = static function(): void { ... };
     * ```
     * 
     * *unregister property closure example:
     * call:
     * ```php
     * $registry->unregisterDeferredByMethod(CacheInvalidationHooks::class, 'purgeCache');
     * ```
     *
     * @template T of Object
     * @param class-string<T> $class  Fully qualified class name.
     * @param key-of<T, string> $method Method or public property name to unregister.
     */
    public function unregisterDeferredByMethod(string $class, string $method): void
    {
        $prefix = $class . '::' . $method . '::';
        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach (array_keys($hookHandlers) as $key) {
                if (str_starts_with($key, $prefix)) {
                    unset($hookHandlers[$key]);
                }
            }
        }
    }

    /**
     * Unregister all handlers for a specific WordPress hook name.
     *
     * Removes every LazyHookHandler that was registered for the given hook,
     * covering both actions and filters on that hook regardless of priority.
     * After this call, `add_action/add_filter` entries are removed from
     * WordPress and the internal handler map is cleaned up.
     *
     * **Example:**
     * ```php
     * $registry->unregisterByHook('save_post');
     * All save_post action and filter registrations are removed
     * ```
     ** types autocomplete DX generated by generate-meta-hooks.php
     * @param string $hook WordPress hook name (e.g. 'init', 'save_post', 'wp_robots').
     */
    public function unregisterByHook(string $hook): void
    {
        foreach ($this->handlers[$hook] ?? [] as $data) {
            $this->removeSingleHook($hook, $data);
        }

        unset($this->handlers[$hook]);
    }

    /**
     * Unregister all hooks belonging to a specific service class.
     *
     * Scans all registered hooks and removes every LazyHookHandler whose
     * owning class matches the given FQCN. Useful for disabling an entire
     * service in one call — e.g. during testing or conditional feature toggles.
     *
     * **Example:**
     * ```php
     * $registry->unregisterByClass(CacheInvalidationHooks::class);
     * All hooks from CacheInvalidationHooks are removed
     * ```
     *
     * @param class-string $class Fully qualified class name (e.g. 'WPLokerBJM\Core\CacheInvalidationHooks').
     */
    public function unregisterByClass(string $class): void
    {
        $prefix = $class . '::';
        foreach ($this->handlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!str_starts_with($key, $prefix)) {
                    continue;
                }
                $this->removeSingleHook($hook, $data);
                unset($hookHandlers[$key]);
            }
        }
        unset($hookHandlers);
    }

    /**
     * Unregister a specific hook method or property on a service class.
     *
     * Targets a single member (method or public property closure) without
     * affecting other hooks registered by the same service.
     *
     * **Examples:**
     *
     * *Method-based:
     * ```php
     * $registry->unregisterByMethod(CacheInvalidationHooks::class, 'purgeCacheOnChange');
     * ```
     *
     * *Property closure:
     * ```php
     * $registry->unregisterByMethod(WPGraphQL::class, 'disableNoCacheHeaders');
     * ```
     *
     * @template T of Object
     * @param class-string<T> $class  Fully qualified class name.
     * @param key-of<T, string> $method Method or public property name to unregister.
     */
    public function unregisterByMethod(string $class, string $method): void
    {
        $prefix = $class . '::' . $method . '::';
        foreach ($this->handlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!str_starts_with($key, $prefix)) {
                    continue;
                }
                $this->removeSingleHook($hook, $data);
                unset($hookHandlers[$key]);
            }
        }
        unset($hookHandlers);
    }

    /**
     * Internal: call add_action or add_filter for a single handler entry.
     *
     * @param string $hook
     * @param HandlerEntry $data
     */
    private function addSingleHook(string $hook, array $data): void
    {
        if ($data['type'] === 'action') {
            add_action($hook, $data['handler'], $data['priority'], $data['accepted_args']);
        } else {
            add_filter($hook, $data['handler'], $data['priority'], $data['accepted_args']);
        }
    }

    /**
     * Internal: call remove_action or remove_filter for a single handler entry.
     *
     * @param RemoveHandlerEntry $data
     */
    private function removeSingleHook(string $hook, array $data): void
    {
        if ($data['type'] === 'action') {
            remove_action($hook, $data['handler'], $data['priority']);
        } else {
            remove_filter($hook, $data['handler'], $data['priority']);
        }
    }
}

/**
 * Scans directories for WordPress hook attribute registrations.
 *
 * This scanner searches for instance methods and properties annotated with
 * #[Action] or #[Filter] attributes across all autowirable PHP classes.
 * The resulting registrations are used by the Init service to automatically
 * register WordPress hooks via the DI container.
 *
 * @see Action
 * @see Filter
 * @see \WPLokerBJM\Bootstrap
 *
 * @phpstan-type HookRegistration array{class: class-string, method: string, type: 'action'|'filter', hook: string, priority: int, accepted_args: int, defer: bool, target: 'method'|'property'|'property-hook', visibility: 'public'|'protected'|'private'}
 */
class WPHooksScanner
{

    /** @var array<int, HookRegistration>|null */
    private ?array $cachedHookRegistrations = null;

    public function __construct(private string $namespace = 'WPLokerBJM')
    {
        $this->namespace = trim($namespace, '\\');
    }

    /**
     * Get hook registrations from #[Action] and #[Filter] attributes.
     *
     * Scans instance methods and properties for hook attributes across all PHP files
     * in the base directory. Results are cached in-memory for the request.
     *
     * @return HookRegistration[]
     */
    public function getHookRegistrations(): array
    {
        if ($this->cachedHookRegistrations !== null) {
            return $this->cachedHookRegistrations;
        }

        $registrations = $this->performHookRegistrationScan();
        $this->cachedHookRegistrations = $registrations;
        return $registrations;
    }

    /**
     * Perform the actual hook registration scanning logic.
     *
     * Scans instance methods and properties across all visibility levels.
     * Static members are intentionally ignored — hooks are resolved through
     * the DI container so the owning service must be instantiable.
     *
     * @return HookRegistration[]
     */
    private function performHookRegistrationScan(): array
    {
        $registrations = [];

        $namespacePrefix = $this->namespace . '\\';

        foreach (Bootstrap::getRobotLoader()->getIndexedClasses() as $className => $file) {
            if (!str_starts_with($className, $namespacePrefix) || !class_exists($className)) {
                continue;
            }
            try {
                $reflection = new ReflectionClass($className);
                /** @var ReflectionMethod $method */
                foreach ($reflection->getMethods(ReflectionMethod::IS_PUBLIC | ReflectionMethod::IS_PROTECTED | ReflectionMethod::IS_PRIVATE) as $method) {
                    // Skip static methods — hooks must be instance methods
                    // because the container resolves the owning service lazily.
                    if ($method->isStatic()) {
                        continue;
                    }
                    $visibility = $method->isPublic() ? 'public' : ($method->isProtected() ? 'protected' : 'private');
                    /** @var \ReflectionAttribute $attribute */
                    foreach ($method->getAttributes(Action::class) as $attribute) {
                        $action = $attribute->newInstance();
                        /** @var Action $action */
                        $registrations[] = [
                            'class' => $className,
                            'method' => $method->getName(),
                            'type' => 'action',
                            'hook' => $action->hook,
                            'priority' => $action->priority,
                            'accepted_args' => $action->acceptedArgs,
                            'defer' => $action->defer,
                            'target' => 'method',
                            'visibility' => $visibility,
                        ];
                    }
                    /** @var \ReflectionAttribute $attribute */
                    foreach ($method->getAttributes(Filter::class) as $attribute) {
                        $filter = $attribute->newInstance();
                        /** @var Filter $filter */
                        $registrations[] = [
                            'class' => $className,
                            'method' => $method->getName(),
                            'type' => 'filter',
                            'hook' => $filter->hook,
                            'priority' => $filter->priority,
                            'accepted_args' => $filter->acceptedArgs,
                            'defer' => $filter->defer,
                            'target' => 'method',
                            'visibility' => $visibility,
                        ];
                    }
                }

                /** @var ReflectionProperty $property */
                foreach ($reflection->getProperties(ReflectionProperty::IS_PUBLIC | ReflectionProperty::IS_PROTECTED | ReflectionProperty::IS_PRIVATE) as $property) {
                    $visibility = $property->isPublic() ? 'public' : ($property->isProtected() ? 'protected' : 'private');
                    $hasPropertyHook = $property->hasHooks();
                    $target = $hasPropertyHook ? 'property-hook' : 'property';
                    foreach ($property->getAttributes(Action::class) as $attribute) {
                        $action = $attribute->newInstance();
                        /** @var Action $action */
                        $registrations[] = [
                            'class' => $className,
                            'method' => $property->getName(),
                            'type' => 'action',
                            'hook' => $action->hook,
                            'priority' => $action->priority,
                            'accepted_args' => $action->acceptedArgs,
                            'defer' => $action->defer,
                            'target' => $target,
                            'visibility' => $visibility,
                        ];
                    }
                    /** @var \ReflectionAttribute $attribute */
                    foreach ($property->getAttributes(Filter::class) as $attribute) {
                        $filter = $attribute->newInstance();
                        /** @var Filter $filter */
                        $registrations[] = [
                            'class' => $className,
                            'method' => $property->getName(),
                            'type' => 'filter',
                            'hook' => $filter->hook,
                            'priority' => $filter->priority,
                            'accepted_args' => $filter->acceptedArgs,
                            'defer' => $filter->defer,
                            'target' => $target,
                            'visibility' => $visibility,
                        ];
                    }
                }
            } catch (\Exception $e) {
                Logger::error('WPhooksScanner', 'Error scanning hooks for class ' . $className . ': ' . $e->getMessage());
            }
        }

        return $registrations;
    }
}