<?php

declare(strict_types=1);
namespace WPLokerBJM\Core\Container\Support\WPHooks;

use ReflectionClass;
use ReflectionFunction;
use DI\Container;
use ReflectionProperty;
use WPLokerBJM\Shared\Log\Logger;
use Psr\Container\ContainerInterface;
use WPLokerBJM\Core\Container\Support\WPHooks\Abstract\{AnonClassHookPropertyAbstract};
use WPLokerBJM\Core\Container\Attributes\{Action, Filter};
use WPLokerBJM\Core\Container\Support\WPHooks\Trait\HookScannerTrait;
use WPLokerBJM\Core\Container\Support\WPHooks\HookRegistration;

/**
 * Registry for WordPress hooks discovered via #[Action] and #[Filter] attributes.
 *
 * Stores all hook registrations as identifiable ContainerLazyHookHandler instances,
 * enabling unregistration by hook name, class, or specific class::method.
 * Service resolution is deferred to hook-fire time (lazy loading).
 *
 * @phpstan-type HandlerEntry array{key: HookKey, handler: ContainerLazyHookHandler|ContainerLazyPropertyHookHandler, type: 'action'|'filter', priority: int, accepted_args: int, tags: array<int, string>}
 * @phpstan-type RemoveHandlerEntry array{handler: ContainerLazyHookHandler|ContainerLazyPropertyHookHandler, type: 'action'|'filter', priority: int}
 * @template TargetClass of Object
 * @phpstan-type HookTargetResolve object<TargetClass>|callable|string|array{object<TargetClass>, string}
 */
class WPHooksContainerRegistry
{
    /**
     * @var array<string, array<string, HandlerEntry>>
     */
    private array $handlers = [];

    /**
     * Deferred handlers not yet registered with WordPress.
     *
     * @var array<string, array<string, HandlerEntry>>
     */
    private array $deferredHandlers = [];

    private bool $initialized = false;

    /**
     * @param ContainerInterface $container
     * @param HookRegistration[] $hooksRegistration
     * @param WPHookPlanProvider|null $hookPlanProvider Plan provider for condition/hook-name resolution.
     */
    public function __construct(
        private readonly ContainerInterface $container,
        private array $hooksRegistration,
        private WPHookPlanProvider $planProvider,
    ) {
    }

    /**
     * Register all stored hooks with WordPress via add_action/add_filter.
     */
    public function initialize(): void
    {
        if ($this->initialized) {
            return;
        }
        $this->registerAll($this->hooksRegistration);
        foreach ($this->handlers as $hook => $hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                try {
                    $this->addSingleHook($hook, $data);
                } catch (\Exception $e) {
                    Logger::error(
                        'WPHooksContainerRegistry',
                        "Error registering {$data['type']} '{$hook}' for {$key}: {$e->getMessage()}"
                    );
                }
            }
        }

        $this->initialized = true;
    }

    #region deferred handlers activation methods

    /**
     * Activate all deferred handlers registered for a specific WordPress hook.
     *
     * Moves matching ContainerLazyHookHandler instances from $this->deferredHandlers
     * into $this->handlers and registers them with WordPress via add_action/add_filter.
     * Handlers that have already been activated are silently skipped.
     *
     * **Example:**
     * ```php
     * $registry->activateDeferredByHook('init');
     * ```
     ** types autocomplete DX generated by generate-meta-hooks.php
     * @param string $hook WordPress hook name.
     */
    public function activateDeferredByHook(string $hook): void
    {
        if (empty($this->deferredHandlers[$hook])) {
            return;
        }

        foreach ($this->deferredHandlers[$hook] as $key => $data) {
            // Guard: skip if already activated
            if (isset($this->handlers[$hook][$key])) {
                continue;
            }

            $this->handlers[$hook][$key] = $data;

            $this->addSingleHook($hook, $data);
        }

        unset($this->deferredHandlers[$hook]);
    }

    /**
     * Activate all deferred handlers belonging to a specific service class.
     *
     * Scans all deferred hooks and activates any ContainerLazyHookHandler whose owning
     * class matches the given FQCN. Already-active handlers are silently skipped.
     *
     * **Example:**
     * ```php
     * $registry->activateDeferredByClass(WPGraphQL::class);
     * ```
     *
     * @param class-string $class Fully qualified class name.
     */
    public function activateDeferredByClass(string $class): void
    {
        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!$data['key']->isForClass($class)) {
                    continue;
                }

                // Guard: skip if already activated
                if (isset($this->handlers[$hook][$key])) {
                    unset($hookHandlers[$key]);
                    continue;
                }

                $this->handlers[$hook][$key] = $data;

                $this->addSingleHook($hook, $data);

                unset($hookHandlers[$key]);
            }
            if (empty($hookHandlers)) {
                unset($this->deferredHandlers[$hook]);
            }
        }
        unset($hookHandlers);
    }

    /**
     * Activate deferred hook handlers matching the specified target callable or identifier.
     *
     * Scans the deferred handlers pool and transfers matching entries to the active pool,
     * registering them immediately with WordPress via `add_action()` or `add_filter()`.
     * Works seamlessly across standard instance methods, first-class callables, PHP 8.4
     * property hooks, array targets, and class-string identifiers.
     *
     * Already-activated handlers are silently skipped to prevent duplicate registrations.
     *
     * **Usage Examples:**
     *
     ** 1. First-Class Callable (Recommended for External Orchestrators):
     * Provides full IDE autocompletion, type safety, and static refactoring support.
     * ```php
     *! $registry->activateDeferredByCallable($this->graphQL->setCacheHeader(...));
     * ```
     *
     ** 2. Self-Referencing Array (Recommended for Internal Method Self-Activation):
     * Fast-path resolution when a method manages its own hook status. DRY and refactor-proof via `__FUNCTION__`.
     * ```php
     *! $registry->activateDeferredByCallable([$this, __FUNCTION__]);
     * ```
     *
     ** 3. String Identifier (Class::method):**
     * Useful for static activation or when an active instance reference is not readily available.
     * ```php
     *! $registry->activateDeferredByCallable(GraphQLService::class . '::setCacheHeader');
     * ```
     *
     ** 4. Array Lookup (`[$object, 'method']`):**
     * Traditional PHP callable array syntax for instance method target resolution.
     * ```php
     *! $registry->activateDeferredByCallable([$this->graphQL, 'setCacheHeader']);
     * ```
     *
     ** 5. PHP 8.4 Property Hooks & Dynamic Invokables & PHP 8.5 inline closure constant expression:**
     * Activates closures or invokable objects held within class properties.
     * On property: 
     * ```php
     * private $disableNoCacheHeaders = static function() { return false; };
     *
     *! $registry->activateDeferredByCallable($this->graphQL->disableNoCacheHeaders);
     * ```
     *
     * @param HookTargetResolve $target First-class callable, array `[$object, 'method']`,
     *                                  string `'Class::method'`, or invokable property reference.
     *
     * @return void
     * @throws \InvalidArgumentException If the target cannot be resolved to a valid class and member.
     */
    public function activateDeferredByCallable(callable|string|array $target): void
    {
        [$class, $method] = ($this->resolverTarget)($target);
        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!$data['key']->isForCallable($class, $method)) {
                    continue;
                }

                if (isset($this->handlers[$hook][$key])) {
                    unset($hookHandlers[$key]);
                    continue;
                }

                $this->handlers[$hook][$key] = $data;
                $this->addSingleHook($hook, $data);
                unset($hookHandlers[$key]);
            }
            if (empty($hookHandlers)) {
                unset($this->deferredHandlers[$hook]);
            }
        }
        unset($hookHandlers);
    }

    /**
     * Activate all deferred handlers carrying at least one of the given tags.
     *
     * Scans the deferred handlers pool and transfers matching entries to the
     * active pool, registering them immediately with WordPress. Accepts a
     * single tag string or an array of tags — a hook matches when any of its
     * tags intersects the query set. Already-active handlers are silently
     * skipped.
     *
     * **Example:**
     * ```php
     * $registry->activateDeferredByTags(['cache', 'seo']);
     * $registry->activateDeferredByTags('cache');
     * ```
     *
     * @param array<string> $tags Tag or list of tags to activate.
     * @return int Number of handlers activated.
     */
    public function activateDeferredByTags(array $tags): int
    {
        if ($tags === []) {
            return 0;
        }

        $activated = 0;
        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (array_intersect($tags, $data['tags']) === []) {
                    continue;
                }

                // Guard: skip if already activated
                if (isset($this->handlers[$hook][$key])) {
                    unset($hookHandlers[$key]);
                    continue;
                }

                $this->handlers[$hook][$key] = $data;
                $this->addSingleHook($hook, $data);
                unset($hookHandlers[$key]);
                $activated++;
            }
            if (empty($hookHandlers)) {
                unset($this->deferredHandlers[$hook]);
            }
        }
        unset($hookHandlers);

        return $activated;
    }
    #endregion

    #region deferred handlers unregisteration methods
    /**
     * Unregister a deferred hook using a first-class callable, array lookup,
     * or class-string identifier.
     *
     * @param HookTargetResolve $target
     */
    public function unregisterDeferredByCallable(callable|string|array $target): void
    {
        [$class, $method] = ($this->resolverTarget)($target);

        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if ($data['key']->isForCallable($class, $method)) {
                    unset($hookHandlers[$key]);
                }
            }
        }
    }

    /**
     * Unregister all deferred handlers for a specific WordPress hook name.
     *
     * @param string $hook WordPress hook name.
     */
    public function unregisterDeferredByHook(string $hook): void
    {
        unset($this->deferredHandlers[$hook]);
    }

    /**
     * Unregister all deferred hooks belonging to a specific service class.
     *
     * @param class-string $class Fully qualified class name.
     */
    public function unregisterDeferredByClass(string $class): void
    {
        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if ($data['key']->isForClass($class)) {
                    unset($hookHandlers[$key]);
                }
            }
        }
    }

    /**
     * Unregister all deferred handlers carrying at least one of the given tags.
     *
     * Only touches the deferred pool — active handlers are never affected.
     * Accepts a single tag string or an array of tags; a hook matches when any
     * of its tags intersects the query set.
     *
     * @param array<string> $tags Tag or list of tags to unregister.
     */
    public function unregisterDeferredByTags(array $tags): void
    {

        if ($tags === []) {
            return;
        }

        foreach ($this->deferredHandlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (array_intersect($tags, $data['tags']) !== []) {
                    unset($hookHandlers[$key]);
                }
            }
            if (empty($hookHandlers)) {
                unset($this->deferredHandlers[$hook]);
            }
        }
        unset($hookHandlers);
    }
    #endregion
    #region main handlers unregisteration methods
    /**
     * Unregister a registered hook via first-class callable, array lookup,
     * or class-string identifier.
     *
     * @param HookTargetResolve $target
     */
    public function unregisterByCallable(callable|string|array $target): void
    {
        [$class, $method] = ($this->resolverTarget)($target);

        foreach ($this->handlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!$data['key']->isForCallable($class, $method)) {
                    continue;
                }
                $this->removeSingleHook($hook, $data);
                unset($hookHandlers[$key]);
            }
        }
        unset($hookHandlers);
    }

    /**
     * Unregister all handlers for a specific WordPress hook name.
     *
     * @param string $hook WordPress hook name.
     */
    public function unregisterByHook(string $hook): void
    {
        foreach ($this->handlers[$hook] ?? [] as $data) {
            $this->removeSingleHook($hook, $data);
        }

        unset($this->handlers[$hook]);
    }

    /**
     * Unregister all hooks belonging to a specific service class.
     *
     * @param class-string $class Fully qualified class name.
     */
    public function unregisterByClass(string $class): void
    {
        foreach ($this->handlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (!$data['key']->isForClass($class)) {
                    continue;
                }
                $this->removeSingleHook($hook, $data);
                unset($hookHandlers[$key]);
            }
        }
        unset($hookHandlers);
    }

    /**
     * Unregister all active handlers carrying at least one of the given tags.
     *
     * Only touches the active pool — deferred handlers are never affected.
     * Accepts a single tag string or an array of tags; a hook matches when any
     * of its tags intersects the query set.
     *
     * @param array<string> $tags Tag or list of tags to unregister.
     */
    public function unregisterByTags(array $tags): void
    {
        if ($tags === []) {
            return;
        }

        foreach ($this->handlers as $hook => &$hookHandlers) {
            foreach ($hookHandlers as $key => $data) {
                if (array_intersect($tags, $data['tags']) === []) {
                    continue;
                }
                $this->removeSingleHook($hook, $data);
                unset($hookHandlers[$key]);
            }
            if (empty($hookHandlers)) {
                unset($this->handlers[$hook]);
            }
        }
        unset($hookHandlers);
    }
    #endregion

    #region Resolver Target Logics
    /**
     * Lazily-created callable target resolver.
     *
     * Implemented as an anonymous invokable object so it can serve as
     * demonstration of invokable object(class) and encapsulate per-request state
     * Resolves supported hook targets:
     *  - first-class callables
     *  - [$object, 'method']
     *  - 'Class::method'
     *  - invokable objects
     *  - PHP 8.4 property hook closures
     *
     * @return callable(HookTargetResolve): array{class-string, string}
     */
    private $resolverTarget {
        get => $this->resolverTarget ??= new class () {
            /**
             * Per-request cache of resolved callable → [FQCN, memberName].
             *
             * WeakMap automatically drops entries when their key (the callable
             * object) is garbage-collected, avoiding memory leaks.
             *
             * @var \WeakMap<object, array{class-string, string}>
             */
            private \WeakMap $callableTargetCache;

            public function __construct()
            {
                $this->callableTargetCache = new \WeakMap();
            }

            /**
             * @param HookTargetResolve $target
             * @return array{class-string, string}
             */
            public function __invoke(object|callable|array|string $target): array
            {
                if (is_object($target) && isset($this->callableTargetCache[$target])) {
                    return $this->callableTargetCache[$target];
                }

                $result = $this->doResolveCallableTarget($target);

                if (is_object($target)) {
                    $this->callableTargetCache[$target] = $result;
                }
                return $result;
            }
            /**
             * @param HookTargetResolve $target
             * @return array{class-string, string}
             */
            private function doResolveCallableTarget(object|callable|array|string $target): array
            {
                // 1. Array [$object, 'memberName'] — fast path
                if (is_array($target)) {
                    return [get_class($target[0]), $target[1]];
                }

                // 2. String 'Class::method' — static fallback
                if (is_string($target)) {
                    $parts = explode('::', $target, 2);
                    return [$parts[0], $parts[1] ?? '__invoke'];
                }

                // 3. Invokable Object Instance (anonymous class from a property)
                if (!$target instanceof \Closure && is_object($target)) {
                    return $this->analyseObject($target);
                }

                // 4. Closure (First-class callable or PHP 8.4 property hook accessor)
                $ref = new \ReflectionFunction($target);
                $calledClass = $ref->getClosureCalledClass()?->getName();

                if ($calledClass === null) {
                    throw new \InvalidArgumentException('Callable target must be bound to an object instance.');
                }

                $name = $ref->getName();

                // Standard Instance Method ($service->method(...))
                if (!str_contains($name, '{closure')) {
                    return [$calledClass, $name];
                }

                // PHP 8.4 Property Hook Closure ("{closure:FQCN::$propertyName::get():line}")
                if (str_contains($name, '::$')) {
                    $start = strpos($name, '::$') + 3;
                    $end = strpos($name, '::', $start);

                    if ($start !== false && $end !== false) {
                        return [$calledClass, substr($name, $start, $end - $start)];
                    }
                }

                throw new \InvalidArgumentException("Unable to resolve hook target for class {$calledClass}.");
            }

            /**
             * 
             * @param object $target
             * @return array{class-string, string}
             */
            private function analyseObject(object $target): array
            {
                $className = $target::class;

                // Anonymous class extending AnonClassHookPropertyAbstract —
                // reads parent class & property directly, no backtrace needed.
                if ($target instanceof AnonClassHookPropertyAbstract) {
                    return [$target->parentClass, $target->parentProperty];
                }

                // Best-effort fallback for anonymous classes that don't
                // extend the AnonClassHookPropertyAbstract: walk the call stack to find which
                // object's property holds this instance.
                if ((new \ReflectionClass($target))->isAnonymous()) {
                    $backtrace = debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT, 10);
                    foreach ($backtrace as $frame) {
                        $callerObject = $frame['object'] ?? null;
                        if ($callerObject === null) {
                            continue;
                        }
                        $refClass = new \ReflectionClass($callerObject);
                        /** @var \ReflectionProperty $property */
                        foreach ($refClass->getProperties() as $property) {
                            if ($property->isInitialized($callerObject) && $property->getValue($callerObject) === $target) {
                                Logger::warning("WPHooksContainerRegistry: ", "Anon class without extending AnonClassHookPropertyAbstract, it's recommended to use 'AnonClassHookPropertyAbstract'." . $refClass->getName() . "::" . $property->getName());
                                return [$refClass->getName(), $property->getName()];
                            }
                        }
                    }
                }

                return [$className, '__invoke'];
            }
        };
    }

    #endregion
    /**
     * Internal: call add_action or add_filter for a single handler entry.
     *
     * @param string $hook
     * @param HandlerEntry $data
     */
    private function addSingleHook(string $hook, array $data): void
    {
        if ($data['type'] === 'action') {
            add_action($hook, $data['handler'], $data['priority'], $data['accepted_args']);
        } else {
            add_filter($hook, $data['handler'], $data['priority'], $data['accepted_args']);
        }
    }

    /**
     * Internal: call remove_action or remove_filter for a single handler entry.
     *
     * @param RemoveHandlerEntry $data
     */
    private function removeSingleHook(string $hook, array $data): void
    {
        if ($data['type'] === 'action') {
            remove_action($hook, $data['handler'], $data['priority']);
        } else {
            remove_filter($hook, $data['handler'], $data['priority']);
        }
    }

    /**
     * Resolve the final hook name for a registration.
     *
     * A plain string is used as-is; a closure is resolved through the DI
     * container (via the plan provider) and must return a string.
     *
     * @throws \RuntimeException when the closure result is not a string
     */
    private function resolveHookName(string|\Closure $hook, array $hookParams, string $label): string
    {
        if (is_string($hook)) {
            return $hook;
        }

        $values = $this->planProvider->resolveCallableParameters($hook, $hookParams, $this->container, $label);
        $name = $hook(...$values);

        if (!is_string($name)) {
            throw new \RuntimeException(
                'Hook name for ' . $label . ' must return string, got ' . get_debug_type($name)
            );
        }

        return $name;
    }

    /**
     * Register hook registrations from the scanner.
     * Pre-builds ContainerLazyHookHandler instances and validates container existence.
     *
     * @param HookRegistration[] $registrations
     */
    private function registerAll(array|HookRegistration $registrations): void
    {
        foreach ($registrations as $reg) {
            $registration = $reg instanceof HookRegistration ? $reg : HookRegistration::fromArray($reg);

            if (!$this->container->has($registration->class)) {
                Logger::warning(
                    'WPHooksContainerRegistry',
                    'Skipping hook ' . $registration->hook
                    . ' — class not in container: ' . $registration->class
                );
                continue;
            }

            try {
                $hookName = $this->resolveHookName(
                    $registration->hook,
                    $registration->hookParams,
                    $registration->class . '::' . $registration->method
                );
            } catch (\RuntimeException $e) {
                Logger::error(
                    'WPHooksContainerRegistry',
                    'Skipping hook for ' . $registration->class . '::' . $registration->method . ' — ' . $e->getMessage()
                );
                continue;
            }

            $handler = $registration->target === 'method'
                ? new ContainerLazyHookHandler($this->container, $registration->class, $registration->method, $registration->visibility, $registration->type, $registration->condition, $registration->conditionParams, $this->planProvider)
                : new ContainerLazyPropertyHookHandler($this->container, $registration->class, $registration->method, $registration->visibility, $registration->type, $registration->condition, $registration->conditionParams, $this->planProvider);
            $key = HookKey::fromRegistration($registration);
            $target = $registration->defer ? 'deferredHandlers' : 'handlers';
            $this->{$target}[$hookName][$key->toString()] = [
                'key' => $key,
                'handler' => $handler,
                'type' => $registration->type,
                'priority' => $registration->priority,
                'accepted_args' => $registration->acceptedArgs,
                'tags' => $registration->tags,
            ];
        }
    }
}

/**
 * Runtime hook registry for on-the-fly object hook registration.
 *
 ** Unlike WPHooksContainerRegistry (which works with file-scanned, container-resolved
 ** classes), this registry registers hooks immediately from an already-
 ** instantiated object. This enables hook registration for anonymous classes
 ** and dynamically-created objects that cannot be discovered by the file-based
 ** WPHooksScanner.
 *
 * Usage:
 *   $service = new class($this->registry) {
 *       #[Action(hook: 'init')]
 *       public function __construct(WPHooksRuntimeRegistry $registry) { 
 *           $registry->registerHooksOn($this); // register
 *           $registry->unregisterHooksOn($this); // unregister (optional)
 *       }
 *       public function onInit(): void { ... }
 *   };
 *
 *! All attribute hooks are registered eagerly — the `defer` & 'condition' flags are
 *! ignored on the attribute path (no container access), and static methods are
 *! silently skipped.
 ** But for compensation:
 *! Manual registration (registerAction() / registerFilter()) is the escape hatch
 *! for runtime state: hook names, callbacks and condition closures may capture
 *! the surrounding scope directly, and `condition` closures ARE supported there
 *! (invoked directly, must return bool).
 *
 */
class WPHooksRuntimeRegistry
{
    use HookScannerTrait;

    /**
     * Maps owner objects to their registered hook metadata and handlers.
     *
     * Every registration — attribute-discovered or manual — is owned by exactly
     * one object; unregisterHooksOn($owner) removes all of them at once.
     *
     * @var \WeakMap<object, list<array{
     *     handler: RuntimeInstanceHookHandler|RuntimeInstancePropertyHookHandler|RuntimeCallableHookHandler,
     *     hook: string,
     *     priority: int,
     *     type: 'action'|'filter'
     * }>>
     */
    private \WeakMap $registry;

    /**
     * Tracks which owners already had their attributes scanned, so
     * registerHooksOn() runs exactly once per object regardless of the
     * order of manual registerAction()/registerFilter() calls.
     *
     * @var \WeakMap<object, bool>
     */
    private \WeakMap $scanned;

    public function __construct()
    {
        $this->registry = new \WeakMap();
        $this->scanned = new \WeakMap();
    }

    /**
     * Scan and register hooks on the given object instance.
     *
     * Non-static methods and properties annotated with #[Action] or
     * #[Filter] are registered via add_action() / add_filter()
     * immediately. Calling this on an already-registered instance is
     * a no-op.
     *
     * @param object $instance An instantiated object with hook-annotated methods/properties.
     */
    public function registerHooksOn(object $instance): void
    {
        // Attributes are scanned exactly once per owner, no matter how many
        // manual registerAction()/registerFilter() calls ran before or after.
        if (isset($this->scanned[$instance])) {
            return;
        }

        $records = [];
        $ref = new ReflectionClass($instance);

        $this->scanMethodHooks(
            $ref,
            function (\ReflectionMethod $method, Action|Filter $attr, string $visibility, string $type) use ($instance, &$records): void {
                if ($attr->hook instanceof \Closure) {
                    Logger::warning(
                        'WPHooksRuntimeRegistry',
                        'Skipping hook on ' . $method->getName()
                        . ' — closure hooks are unsupported on runtime-registered instances (no container access)'
                    );
                    return;
                }

                if ($attr->condition !== null) {
                    Logger::warning(
                        'WPHooksRuntimeRegistry',
                        'Skipping hook ' . $attr->hook . ' on ' . $method->getName()
                        . ' — condition closures are unsupported on runtime-registered instances (no container access)'
                    );
                    return;
                }

                $handler = new RuntimeInstanceHookHandler(
                    $instance,
                    $method->getName(),
                    $visibility,
                    $type
                );

                if ($type === 'action') {
                    \add_action($attr->hook, $handler, $attr->priority, $attr->acceptedArgs);
                } else {
                    \add_filter($attr->hook, $handler, $attr->priority, $attr->acceptedArgs);
                }

                $records[] = [
                    'handler' => $handler,
                    'hook' => $attr->hook,
                    'priority' => $attr->priority,
                    'type' => $type,
                ];
            }
        );

        $this->scanPropertyHooks(
            $ref,
            function (\ReflectionProperty $property, Action|Filter $attr, string $visibility, string $type, string $target) use ($instance, &$records): void {
                if ($attr->hook instanceof \Closure) {
                    Logger::warning(
                        'WPHooksRuntimeRegistry',
                        'Skipping hook on ' . $property->getName()
                        . ' — closure hooks are unsupported on runtime-registered instances (no container access)'
                    );
                    return;
                }

                if ($attr->condition !== null) {
                    Logger::warning(
                        'WPHooksRuntimeRegistry',
                        'Skipping hook ' . $attr->hook . ' on ' . $property->getName()
                        . ' — condition closures are unsupported on runtime-registered instances (no container access)'
                    );
                    return;
                }

                $handler = new RuntimeInstancePropertyHookHandler(
                    $instance,
                    $property->getName(),
                    $visibility,
                    $type
                );

                if ($type === 'action') {
                    \add_action($attr->hook, $handler, $attr->priority, $attr->acceptedArgs);
                } else {
                    \add_filter($attr->hook, $handler, $attr->priority, $attr->acceptedArgs);
                }

                $records[] = [
                    'handler' => $handler,
                    'hook' => $attr->hook,
                    'priority' => $attr->priority,
                    'type' => $type,
                ];
            }
        );

        $this->scanned[$instance] = true;
        $this->registry[$instance] = array_merge($this->registry[$instance] ?? [], $records);
    }
    /**
     * Remove all hooks previously registered for the given instance.
     *
     * Calls remove_action() / remove_filter() for each registered hook
     * and clears internal tracking. Calling this on an instance that was
     * never registered is a no-op.
     *
     * @param object $instance The instance whose hooks should be removed.
     */
    public function unregisterHooksOn(object $instance): void
    {
        if (!isset($this->registry[$instance])) {
            return;
        }

        foreach ($this->registry[$instance] as $record) {
            if ($record['type'] === 'action') {
                \remove_action($record['hook'], $record['handler'], $record['priority']);
            } else {
                \remove_filter($record['hook'], $record['handler'], $record['priority']);
            }
        }

        unset($this->registry[$instance]);
        unset($this->scanned[$instance]);
    }

    /**
     * Register an action hook manually for an owner object.
     *
     * The owner is resolved from the callback when not given explicitly:
     *   - explicit $owner (always wins when provided);
     *   - `[$object, 'method']` array callables → the object;
     *   - first-class callables / bound closures → the bound `$this`;
     *   - invokable objects → the object itself.
     *
     * The hook name, callback and condition closure may capture the surrounding
     * scope directly — no container is involved on the runtime registry.
     * @template T of callable
     * @param string      $hook        Hook name.
     * @param T           $callback    Callable invoked when the hook fires.
     * @param int         $priority    Hook priority.
     * @param int         $acceptedArgs Number of accepted arguments.
     * @param \Closure|null $condition   Optional gate: invoked directly, must return bool.
     * @param object|null $owner       Owning object (defaults to inference).
     *
     * @throws \RuntimeException when the owner cannot be inferred or the callback is not callable.
     */
    public function registerAction(
        string $hook,
        mixed $callback,
        int $priority = 10,
        int $acceptedArgs = 1,
        ?\Closure $condition = null,
        ?object $owner = null,
    ): void {
        if (!is_callable($callback)) {
            $error = 'Cannot register action hook ' . $hook . ' — callback is not callable.';
            Logger::error('WPHooksRuntimeRegistry', $error);
            throw new \RuntimeException($error);
        }

        $this->register(
            type: 'action',
            hook: $hook,
            callback: $callback,
            priority: $priority,
            acceptedArgs: $acceptedArgs,
            condition: $condition,
            owner: $this->resolveOwner($callback, $owner),
        );
    }

    /**
     * Register a filter hook manually for an owner object.
     *
     * Semantics identical to {@see registerAction()} — the callback result is
     * returned to the filter pipeline, and the original value passes through
     * untouched when the handler (or its condition) fails.
     * @template T of callable
     * @param string $hook Hook name
     * @param T $callback Callable invoked when the hook fires.
     * @param int $priority Hook priority
     * @param int $acceptedArgs Number of accepted arguments.
     * @param \Closure|null $condition Optional gate: invoked directly, must return bool.
     * @param object|null $owner Owning object (defaults to inference).
     * @throws \RuntimeException when the owner cannot be inferred or the callback is not callable.
     */
    public function registerFilter(
        string $hook,
        mixed $callback,
        int $priority = 10,
        int $acceptedArgs = 1,
        ?\Closure $condition = null,
        ?object $owner = null,
    ): void {
        if (!is_callable($callback)) {
            $error = 'Cannot register filter hook ' . $hook . ' — callback is not callable.';
            Logger::error('WPHooksRuntimeRegistry', $error);
            throw new \RuntimeException($error);
        }

        $this->register(
            type: 'filter',
            hook: $hook,
            callback: $callback,
            priority: $priority,
            acceptedArgs: $acceptedArgs,
            condition: $condition,
            owner: $this->resolveOwner($callback, $owner),
        );
    }

    /**
     * Shared core for manual registration: wraps the callback in a
     * RuntimeCallableHookHandler, registers it with WordPress immediately and
     * records it under the owner for lifetime-scoped unregistration.
     *
     * @param string        $type        'action' or 'filter'.
     * @param string        $hook        Hook name.
     * @param callable      $callback    Callable invoked when the hook fires.
     * @param int           $priority    Hook priority.
     * @param int           $acceptedArgs Number of accepted arguments.
     * @param \Closure|null $condition   Optional gate: invoked directly, must return bool.
     * @param object        $owner       Owning object (resolved by the caller).
     *
     * @throws \RuntimeException when the callback is not callable.
     */
    private function register(
        string $type,
        string $hook,
        callable $callback,
        int $priority,
        int $acceptedArgs,
        ?\Closure $condition,
        object $owner,
    ): void {
        if (!is_callable($callback)) {
            $error = 'Cannot register ' . $type . ' hook ' . $hook . ' — callback is not callable.';
            Logger::error('WPHooksRuntimeRegistry', $error);
            throw new \RuntimeException($error);
        }

        // Match WordPress semantics: identical (hook, callback, priority)
        // registrations are deduplicated.
        $existing = $this->registry[$owner] ?? [];
        foreach ($existing as $record) {
            if (
                $record['hook'] === $hook
                && ($record['callback'] ?? null) === $callback
                && $record['priority'] === $priority
            ) {
                return;
            }
        }

        $handler = new RuntimeCallableHookHandler($callback, $condition, $type);

        if ($type === 'action') {
            \add_action($hook, $handler, $priority, $acceptedArgs);
        } else {
            \add_filter($hook, $handler, $priority, $acceptedArgs);
        }

        $existing[] = [
            'handler' => $handler,
            'callback' => $callback,
            'hook' => $hook,
            'priority' => $priority,
            'type' => $type,
        ];
        $this->registry[$owner] = $existing;
    }

    /**
     * Resolve the owner of a manual registration.
     *
     * @param callable    $callback Registration callback.
     * @param object|null $owner    Explicit owner — always wins when provided.
     *
     * @throws \RuntimeException when no owner can be inferred.
     */
    private function resolveOwner(callable $callback, ?object $owner): object
    {
        if ($owner !== null) {
            return $owner;
        }

        if (is_array($callback) && is_object($callback[0] ?? null)) {
            return $callback[0];
        }

        if ($callback instanceof \Closure) {
            $bound = (new ReflectionFunction($callback))->getClosureThis();
            if ($bound !== null) {
                return $bound;
            }

            // Static / unbound closure — nothing to infer the owner from.
            throw new \RuntimeException(
                'Cannot infer owner for hook registration — pass owner: explicitly.'
            );
        }

        if (is_object($callback)) {
            return $callback;
        }

        throw new \RuntimeException(
            'Cannot infer owner for hook registration — pass owner: explicitly.'
        );
    }
}