<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'WPLokerBJM\\Views\\Page\\PasangIklanLokerView' => 'get1',
  'subEntry1' => 'get2',
  'WPLokerBJM\\Views\\Page\\SingleView' => 'get3',
  'subEntry2' => 'get4',
  'subEntry3' => 'get5',
  'subEntry4' => 'get6',
  'WPLokerBJM\\Views\\Page\\HomepageView' => 'get7',
  'subEntry5' => 'get8',
  'subEntry6' => 'get9',
  'subEntry7' => 'get10',
  'subEntry8' => 'get11',
  'WPLokerBJM\\Presenters\\Components\\JobCarousel' => 'get12',
  'subEntry9' => 'get13',
  'subEntry10' => 'get14',
  'WPLokerBJM\\Presenters\\Components\\JobGrid' => 'get15',
  'subEntry11' => 'get16',
  'subEntry12' => 'get17',
  'subEntry13' => 'get18',
  'WPLokerBJM\\Models\\Schema\\CustomFields' => 'get19',
  'subEntry14' => 'get20',
  'WPLokerBJM\\Models\\Schema\\PostTypes' => 'get21',
  'subEntry15' => 'get22',
  'WPLokerBJM\\Models\\Schema\\Taxonomies' => 'get23',
  'subEntry16' => 'get24',
  'WPLokerBJM\\Repositories\\CustomFieldRepository' => 'get25',
  'subEntry17' => 'get26',
  'WPLokerBJM\\Repositories\\TaxonomyRepository' => 'get27',
  'subEntry18' => 'get28',
  'WPLokerBJM\\Repositories\\JobRepository' => 'get29',
  'subEntry19' => 'get30',
  'subEntry20' => 'get31',
  'subEntry21' => 'get32',
  'WPLokerBJM\\Controllers\\REST\\DispatchSSGBuild' => 'get33',
  'subEntry22' => 'get34',
  'subEntry23' => 'get35',
  'WPLokerBJM\\Controllers\\REST\\WPThemeData' => 'get36',
  'subEntry24' => 'get37',
  'subEntry25' => 'get38',
  'WPLokerBJM\\Controllers\\REST\\AutoSuggestionSearch' => 'get39',
  'subEntry26' => 'get40',
  'WPLokerBJM\\Controllers\\REST\\JobBookmark' => 'get41',
  'subEntry27' => 'get42',
  'subEntry28' => 'get43',
  'WPLokerBJM\\Controllers\\REST\\Carousel' => 'get44',
  'subEntry29' => 'get45',
  'subEntry30' => 'get46',
  'WPLokerBJM\\Controllers\\REST\\JobGridController' => 'get47',
  'subEntry31' => 'get48',
  'subEntry32' => 'get49',
  'WPLokerBJM\\Controllers\\REST\\TaxonomyDepth' => 'get50',
  'subEntry33' => 'get51',
  'subEntry34' => 'get52',
  'subEntry35' => 'get53',
  'WPLokerBJM\\Controllers\\REST\\DynamicSearch' => 'get54',
  'subEntry36' => 'get55',
  'subEntry37' => 'get56',
  'WPLokerBJM\\Controllers\\REST\\SingleOverlay' => 'get57',
  'subEntry38' => 'get58',
  'subEntry39' => 'get59',
  'WPLokerBJM\\Controllers\\REST\\LoadMore' => 'get60',
  'subEntry40' => 'get61',
  'subEntry41' => 'get62',
  'WPLokerBJM\\Factories\\JobDataFactory' => 'get63',
  'subEntry42' => 'get64',
  'subEntry43' => 'get65',
  'subEntry44' => 'get66',
  'WPLokerBJM\\Core\\Hooks' => 'get67',
  'subEntry45' => 'get68',
  'subEntry46' => 'get69',
  'WPLokerBJM\\Services\\Job\\JobCacheInvalidation' => 'get70',
  'subEntry47' => 'get71',
  'WPLokerBJM\\Services\\Job\\JobSchemaOrg' => 'get72',
  'subEntry48' => 'get73',
  'subEntry49' => 'get74',
  'WPLokerBJM\\Services\\Taxonomy\\TaxonomyService' => 'get75',
  'subEntry50' => 'get76',
  'WPLokerBJM\\Services\\PostsManagement\\SSG\\PostsCRUDListener' => 'get77',
  'subEntry51' => 'get78',
  'subEntry52' => 'get79',
  'subEntry53' => 'get80',
  'WPLokerBJM\\Services\\PostsManagement\\SSG\\RedirectToSSG' => 'get81',
  'subEntry54' => 'get82',
  'subEntry55' => 'get83',
  'subEntry56' => 'get84',
  'WPLokerBJM\\Services\\Utilities\\SSG\\BotDetection' => 'get85',
  'subEntry57' => 'get86',
  'subEntry58' => 'get87',
  'subEntry59' => 'get88',
  'WPLokerBJM\\Services\\Cron\\CronService' => 'get89',
  'subEntry60' => 'get90',
  'WPLokerBJM\\Services\\REST\\RESTData' => 'get91',
  'subEntry61' => 'get92',
  'subEntry62' => 'get93',
  'WPLokerBJM\\Services\\REST\\RESTRoute' => 'get94',
  'subEntry63' => 'get95',
  'subEntry64' => 'get96',
  'subEntry65' => 'get97',
  'subEntry66' => 'get98',
  'subEntry67' => 'get99',
  'subEntry68' => 'get100',
  'subEntry69' => 'get101',
  'subEntry70' => 'get102',
  'subEntry71' => 'get103',
  'subEntry72' => 'get104',
  'subEntry73' => 'get105',
  'WPLokerBJM\\Services\\Webhooks\\TriggerBuildSSG' => 'get106',
  'subEntry74' => 'get107',
  'WPLokerBJM\\Core\\Container\\Init' => 'get108',
  'WPLokerBJM\\Services\\Utilities\\SSG\\BotRangeFetcher' => 'get109',
  'WPLokerBJM\\Services\\Utilities\\SSG\\DnsResolver' => 'get110',
);

    protected function get2()
    {
        $object = new WPLokerBJM\Views\Page\PasangIklanLokerView();
        return $object;
    }

    protected function get1()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Views\Page\PasangIklanLokerView',
            function () {
                return $this->get2();
            }
        );
        return $object;
    }

    protected function get5()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Job\\JobSchemaOrg');
    }

    protected function get6()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\REST\\RESTData');
    }

    protected function get4()
    {
        $object = new WPLokerBJM\Views\Page\SingleView($this->get5(), $this->get6());
        return $object;
    }

    protected function get3()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Views\Page\SingleView',
            function () {
                return $this->get4();
            }
        );
        return $object;
    }

    protected function get9()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Presenters\\Components\\JobGrid');
    }

    protected function get10()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Presenters\\Components\\JobCarousel');
    }

    protected function get11()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Repositories\\JobRepository');
    }

    protected function get8()
    {
        $object = new WPLokerBJM\Views\Page\HomepageView($this->get9(), $this->get10(), $this->get11());
        return $object;
    }

    protected function get7()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Views\Page\HomepageView',
            function () {
                return $this->get8();
            }
        );
        return $object;
    }

    protected function get14()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Repositories\\JobRepository');
    }

    protected function get13()
    {
        $object = new WPLokerBJM\Presenters\Components\JobCarousel($this->get14());
        return $object;
    }

    protected function get12()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Presenters\Components\JobCarousel',
            function () {
                return $this->get13();
            }
        );
        return $object;
    }

    protected function get17()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Job\\JobSchemaOrg');
    }

    protected function get18()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Repositories\\JobRepository');
    }

    protected function get16()
    {
        $object = new WPLokerBJM\Presenters\Components\JobGrid($this->get17(), $this->get18());
        return $object;
    }

    protected function get15()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Presenters\Components\JobGrid',
            function () {
                return $this->get16();
            }
        );
        return $object;
    }

    protected function get20()
    {
        $object = new WPLokerBJM\Models\Schema\CustomFields();
        return $object;
    }

    protected function get19()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Models\Schema\CustomFields',
            function () {
                return $this->get20();
            }
        );
        return $object;
    }

    protected function get22()
    {
        $object = new WPLokerBJM\Models\Schema\PostTypes();
        return $object;
    }

    protected function get21()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Models\Schema\PostTypes',
            function () {
                return $this->get22();
            }
        );
        return $object;
    }

    protected function get24()
    {
        $object = new WPLokerBJM\Models\Schema\Taxonomies();
        return $object;
    }

    protected function get23()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Models\Schema\Taxonomies',
            function () {
                return $this->get24();
            }
        );
        return $object;
    }

    protected function get26()
    {
        $object = new WPLokerBJM\Repositories\CustomFieldRepository();
        return $object;
    }

    protected function get25()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Repositories\CustomFieldRepository',
            function () {
                return $this->get26();
            }
        );
        return $object;
    }

    protected function get28()
    {
        $object = new WPLokerBJM\Repositories\TaxonomyRepository();
        return $object;
    }

    protected function get27()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Repositories\TaxonomyRepository',
            function () {
                return $this->get28();
            }
        );
        return $object;
    }

    protected function get31()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\REST\\RESTData');
    }

    protected function get32()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Job\\JobSchemaOrg');
    }

    protected function get30()
    {
        $object = new WPLokerBJM\Repositories\JobRepository($this->get31(), $this->get32());
        return $object;
    }

    protected function get29()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Repositories\JobRepository',
            function () {
                return $this->get30();
            }
        );
        return $object;
    }

    protected function get35()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Webhooks\\TriggerBuildSSG');
    }

    protected function get34()
    {
        $object = new WPLokerBJM\Controllers\REST\DispatchSSGBuild($this->get35());
        return $object;
    }

    protected function get33()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Controllers\REST\DispatchSSGBuild',
            function () {
                return $this->get34();
            }
        );
        return $object;
    }

    protected function get38()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\REST\\RESTData');
    }

    protected function get37()
    {
        $object = new WPLokerBJM\Controllers\REST\WPThemeData($this->get38());
        return $object;
    }

    protected function get36()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Controllers\REST\WPThemeData',
            function () {
                return $this->get37();
            }
        );
        return $object;
    }

    protected function get40()
    {
        $object = new WPLokerBJM\Controllers\REST\AutoSuggestionSearch();
        return $object;
    }

    protected function get39()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Controllers\REST\AutoSuggestionSearch',
            function () {
                return $this->get40();
            }
        );
        return $object;
    }

    protected function get43()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\REST\\RESTData');
    }

    protected function get42()
    {
        $object = new WPLokerBJM\Controllers\REST\JobBookmark($this->get43());
        return $object;
    }

    protected function get41()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Controllers\REST\JobBookmark',
            function () {
                return $this->get42();
            }
        );
        return $object;
    }

    protected function get46()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Presenters\\Components\\JobCarousel');
    }

    protected function get45()
    {
        $object = new WPLokerBJM\Controllers\REST\Carousel($this->get46());
        return $object;
    }

    protected function get44()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Controllers\REST\Carousel',
            function () {
                return $this->get45();
            }
        );
        return $object;
    }

    protected function get49()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Presenters\\Components\\JobGrid');
    }

    protected function get48()
    {
        $object = new WPLokerBJM\Controllers\REST\JobGridController($this->get49());
        return $object;
    }

    protected function get47()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Controllers\REST\JobGridController',
            function () {
                return $this->get48();
            }
        );
        return $object;
    }

    protected function get52()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Taxonomy\\TaxonomyService');
    }

    protected function get53()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Repositories\\TaxonomyRepository');
    }

    protected function get51()
    {
        $object = new WPLokerBJM\Controllers\REST\TaxonomyDepth($this->get52(), $this->get53());
        return $object;
    }

    protected function get50()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Controllers\REST\TaxonomyDepth',
            function () {
                return $this->get51();
            }
        );
        return $object;
    }

    protected function get56()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Repositories\\JobRepository');
    }

    protected function get55()
    {
        $object = new WPLokerBJM\Controllers\REST\DynamicSearch($this->get56());
        return $object;
    }

    protected function get54()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Controllers\REST\DynamicSearch',
            function () {
                return $this->get55();
            }
        );
        return $object;
    }

    protected function get59()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\REST\\RESTData');
    }

    protected function get58()
    {
        $object = new WPLokerBJM\Controllers\REST\SingleOverlay($this->get59());
        return $object;
    }

    protected function get57()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Controllers\REST\SingleOverlay',
            function () {
                return $this->get58();
            }
        );
        return $object;
    }

    protected function get62()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Repositories\\JobRepository');
    }

    protected function get61()
    {
        $object = new WPLokerBJM\Controllers\REST\LoadMore($this->get62());
        return $object;
    }

    protected function get60()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Controllers\REST\LoadMore',
            function () {
                return $this->get61();
            }
        );
        return $object;
    }

    protected function get65()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Repositories\\CustomFieldRepository');
    }

    protected function get66()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Repositories\\TaxonomyRepository');
    }

    protected function get64()
    {
        $object = new WPLokerBJM\Factories\JobDataFactory($this->get65(), $this->get66());
        return $object;
    }

    protected function get63()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Factories\JobDataFactory',
            function () {
                return $this->get64();
            }
        );
        return $object;
    }

    protected function get69()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Utilities\\SSG\\BotDetection');
    }

    protected function get68()
    {
        $object = new WPLokerBJM\Core\Hooks($this->get69());
        return $object;
    }

    protected function get67()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Core\Hooks',
            function () {
                return $this->get68();
            }
        );
        return $object;
    }

    protected function get71()
    {
        $object = new WPLokerBJM\Services\Job\JobCacheInvalidation();
        return $object;
    }

    protected function get70()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Services\Job\JobCacheInvalidation',
            function () {
                return $this->get71();
            }
        );
        return $object;
    }

    protected function get74()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Factories\\JobDataFactory');
    }

    protected function get73()
    {
        $object = new WPLokerBJM\Services\Job\JobSchemaOrg($this->get74());
        return $object;
    }

    protected function get72()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Services\Job\JobSchemaOrg',
            function () {
                return $this->get73();
            }
        );
        return $object;
    }

    protected function get76()
    {
        $object = new WPLokerBJM\Services\Taxonomy\TaxonomyService();
        return $object;
    }

    protected function get75()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Services\Taxonomy\TaxonomyService',
            function () {
                return $this->get76();
            }
        );
        return $object;
    }

    protected function get79()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Webhooks\\TriggerBuildSSG');
    }

    protected function get80()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Utilities\\SSG\\BotDetection');
    }

    protected function get78()
    {
        $object = new WPLokerBJM\Services\PostsManagement\SSG\PostsCRUDListener($this->get79(), $this->get80());
        return $object;
    }

    protected function get77()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Services\PostsManagement\SSG\PostsCRUDListener',
            function () {
                return $this->get78();
            }
        );
        return $object;
    }

    protected function get83()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Utilities\\SSG\\BotDetection');
    }

    protected function get84()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Webhooks\\TriggerBuildSSG');
    }

    protected function get82()
    {
        $object = new WPLokerBJM\Services\PostsManagement\SSG\RedirectToSSG($this->get83(), $this->get84());
        return $object;
    }

    protected function get81()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Services\PostsManagement\SSG\RedirectToSSG',
            function () {
                return $this->get82();
            }
        );
        return $object;
    }

    protected function get87()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Utilities\\SSG\\BotRangeFetcher');
    }

    protected function get88()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Services\\Utilities\\SSG\\DnsResolver');
    }

    protected function get86()
    {
        $object = new WPLokerBJM\Services\Utilities\SSG\BotDetection($this->get87(), $this->get88());
        return $object;
    }

    protected function get85()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Services\Utilities\SSG\BotDetection',
            function () {
                return $this->get86();
            }
        );
        return $object;
    }

    protected function get90()
    {
        $object = new WPLokerBJM\Services\Cron\CronService();
        return $object;
    }

    protected function get89()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Services\Cron\CronService',
            function () {
                return $this->get90();
            }
        );
        return $object;
    }

    protected function get93()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Factories\\JobDataFactory');
    }

    protected function get92()
    {
        $object = new WPLokerBJM\Services\REST\RESTData($this->get93());
        return $object;
    }

    protected function get91()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Services\REST\RESTData',
            function () {
                return $this->get92();
            }
        );
        return $object;
    }

    protected function get96()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Controllers\\REST\\TaxonomyDepth');
    }

    protected function get97()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Controllers\\REST\\AutoSuggestionSearch');
    }

    protected function get98()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Controllers\\REST\\LoadMore');
    }

    protected function get99()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Controllers\\REST\\Carousel');
    }

    protected function get100()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Controllers\\REST\\DynamicSearch');
    }

    protected function get101()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Controllers\\REST\\SingleOverlay');
    }

    protected function get102()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Controllers\\REST\\DispatchSSGBuild');
    }

    protected function get103()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Controllers\\REST\\JobBookmark');
    }

    protected function get104()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Controllers\\REST\\JobGridController');
    }

    protected function get105()
    {
        return $this->delegateContainer->get('WPLokerBJM\\Controllers\\REST\\WPThemeData');
    }

    protected function get95()
    {
        $object = new WPLokerBJM\Services\REST\RESTRoute($this->get96(), $this->get97(), $this->get98(), $this->get99(), $this->get100(), $this->get101(), $this->get102(), $this->get103(), $this->get104(), $this->get105());
        return $object;
    }

    protected function get94()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Services\REST\RESTRoute',
            function () {
                return $this->get95();
            }
        );
        return $object;
    }

    protected function get107()
    {
        $object = new WPLokerBJM\Services\Webhooks\TriggerBuildSSG([
        ]);
        return $object;
    }

    protected function get106()
    {
                $object = $this->proxyFactory->createProxy(
            'WPLokerBJM\Services\Webhooks\TriggerBuildSSG',
            function () {
                return $this->get107();
            }
        );
        return $object;
    }

    protected function get108()
    {
        return $this->resolveFactory(static function ($c) {
                // Automatically find all autowirable classes that implement HooksInterface
                $scanner = new \WPLokerBJM\Core\Container\AutowireScanner(
                    get_stylesheet_directory() . '/server', // Points to the server/ directory
                    'WPLokerBJM'
                );

                $hooksImplementers = $scanner->getInterfaceImplementerClassNames(
                    \WPLokerBJM\Contracts\HooksInterface::class
                );

                // Resolve each service from the container
                $services = array_map(fn($className) => $c->get($className), $hooksImplementers);

                return new \WPLokerBJM\Core\Container\Init($services);
            }, 'WPLokerBJM\\Core\\Container\\Init');
    }

    protected function get109()
    {
        $object = new WPLokerBJM\Services\Utilities\SSG\BotRangeFetcher();
        return $object;
    }

    protected function get110()
    {
        $object = new WPLokerBJM\Services\Utilities\SSG\DnsResolver();
        return $object;
    }

}
