<?php

declare(strict_types=1);

use Psl\Async\TimeoutCancellationToken;
use Psl\DateTime\Duration;
use Psl\File;
use Psl\File\WriteMode;
use Psl\Filesystem;
use Psl\Iter;
use Psl\Shell;
use Psl\Shell\Exception\FailedExecutionException;
use Psl\Str;
use Psl\Vec;

// ── Helpers ────────────────────────────────────────────────────────────────

/**
 * Run a WP-CLI command inside the Docker container.
 *
 * @param list<string> $arguments wp subcommand arguments
 */
function runWpCli(string $container, string $wpPath, array $arguments): string
{
    return Shell\execute('docker', [
        'exec',
        $container,
        'gosu',
        'wordpress',
        'wp',
        '--path=' . $wpPath,
        ...$arguments,
    ], cancellation: new TimeoutCancellationToken(Duration::seconds(DOCKER_TIMEOUT)));
}

/**
 * Find a running WordPress Docker container.
 *
 * @param list<string> $names Container names to try.
 */
function findContainer(array $names = CONTAINER_NAMES): ?string
{
    $output = Shell\execute('docker', [
        'ps',
        '--format={{.Names}}',
    ], cancellation: new TimeoutCancellationToken(Duration::seconds(DOCKER_PS_TIMEOUT)));

    $running = Vec\filter(
        parseLines($output),
        static fn(string $name): bool => $name !== '',
    );

    foreach ($names as $name) {
        if (Iter\any($running, static fn(string $r): bool => $r === $name)) {
            return $name;
        }
    }
    return null;
}

/**
 * Split a multi-line string into non-empty trimmed lines.
 *
 * @return list<string>
 */
function parseLines(string $input): array
{
    return Vec\filter(
        Vec\map(
            Str\split(Str\trim($input), "\n"),
            Str\trim(...),
        ),
        static fn(string $line): bool => $line !== '',
    );
}

/**
 * Remove duplicates, template hooks ({$...}), trim, sort.
 *
 * @param list<string> $hooks
 * @return list<string>
 */
function normalizeHooks(array $hooks): array
{
    return Vec\sort(
        Vec\filter(
            Vec\unique($hooks),
            static fn(string $h): bool => !Str\contains($h, '{$'),
        ),
    );
}

/**
 * Find PHP files recursively, skipping vendor/node_modules.
 *
 * @return list<string>
 */
function findPhpFiles(string $dir): array
{
    $files = [];
    $it = new \RecursiveIteratorIterator(
        new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
    );
    foreach ($it as $file) {
        /** @var \SplFileInfo $file */
        if (!$file->isFile() || $file->getExtension() !== 'php') {
            continue;
        }
        $path = $file->getPathname();
        if (Iter\any(SKIP_DIRS, static fn(string $d): bool => Str\contains($path, $d))) {
            continue;
        }
        $files[] = $path;
    }
    return $files;
}

// ── Render helpers ─────────────────────────────────────────────────────────

/**
 * Render a hook list as escaped, chunked, comma-separated lines.
 *
 * @param list<string> $hooks
 * @return list<string>
 */
function renderHookLines(array $hooks): array
{
    return Vec\map(
        Vec\chunk($hooks, CHUNK_SIZE),
        static fn(array $chunk): string => '        '
        . Str\join(
            Vec\map(
                $chunk,
                static fn(string $h): string => "'" . Str\replace($h, "'", "\\'") . "'",
            ),
            ', ',
        )
        . ',',
    );
}

/**
 * Build a single expectedArguments() block.
 *
 * @param list<string> $hooks
 */
function renderExpectedArguments(string $target, array $hooks): string
{
    $lines = renderHookLines($hooks);

    return "    expectedArguments(\n        {$target},\n        0,\n"
        . Str\join($lines, "\n") . "\n    );";
}

/**
 * @param list<string> $hooks
 */
function renderArgumentsSet(string $setName, array $hooks): string
{
    $lines = renderHookLines($hooks);

    return "    registerArgumentsSet('{$setName}',\n"
        . Str\join($lines, "\n") . "\n    );";
}

/**
 * Create a boilerplate .phpstorm.meta.php file.
 */
function createBoilerplate(): string
{
    return "<?php\nnamespace PHPSTORM_META {\n\n"
        . "    // === DO NOT EDIT BETWEEN THESE MARKERS — auto-generated by generate-meta-hooks ===\n"
        . "    // BEGIN-AUTO-GENERATED\n"
        . "    // END-AUTO-GENERATED\n"
        . "}\n";
}

/**
 * Render metadata blocks using registerArgumentsSet for DRY hook lists.
 *
 * Defines sets once, then references them via argumentsSet() in each
 * expectedArguments() block — no more repeating the same long lists.
 *
 * @param list<string> $actions
 * @param list<string> $filters
 */
function renderMetadataSection(array $actions, array $filters): string
{
    $result = '';
    $unit = 0;
    $listHooksAction = 'wp_hooks_actions';
    $listHooksFilter = 'wp_hooks_filters';

    // ── 1. registerArgumentsSet: actions ────────────────────────────────
    $unit++;
    $result .= "    // Unit #{$unit}: registerArgumentsSet — action hooks\n";
    $result .= renderArgumentsSet($listHooksAction, $actions) . "\n\n";

    // ── 2. registerArgumentsSet: filters ────────────────────────────────
    $unit++;
    $result .= "    // Unit #{$unit}: registerArgumentsSet — filter hooks\n";
    $result .= renderArgumentsSet($listHooksFilter, $filters) . "\n\n";

    // ── 3. expectedArguments blocks referencing the sets ────────────────
    // NOTE: argumentsSet() CANNOT nest inside registerArgumentsSet() in
    // Intelephense. For methods that need both + filters, we pass multiple
    // argumentsSet() calls as separate positional args
    $expectedBlocks = [
        'Action hooks for #[Action] attribute' => [
            '\\WPLokerBJM\\Core\\Container\\Attributes\\Action::__construct()',
            ["argumentsSet('{$listHooksAction}')"],
        ],
        'Filter hooks for #[Filter] attribute' => [
            '\\WPLokerBJM\\Core\\Container\\Attributes\\Filter::__construct()',
            ["argumentsSet('{$listHooksFilter}')"],
        ],
        'Hooks for \do_action()' => [
            '\do_action()',
            ["argumentsSet('{$listHooksAction}')"],
        ],
        'Hooks for \apply_filters()' => [
            '\apply_filters()',
            ["argumentsSet('{$listHooksFilter}')"],
        ],
        'Hooks for \add_action()' => [
            '\add_action()',
            ["argumentsSet('{$listHooksAction}')"],
        ],
        'Hooks for \add_filter()' => [
            '\add_filter()',
            ["argumentsSet('{$listHooksFilter}')"],
        ],
        'List hooks (deferred) to register' => [
            '\\WPLokerBJM\\Core\\Container\\Support\\WPHooksRegistry::activateDeferredByHook()',
            ["argumentsSet('{$listHooksAction}')", "argumentsSet('{$listHooksFilter}')"],
        ],
        'List hooks to unregister' => [
            '\\WPLokerBJM\\Core\\Container\\Support\\WPHooksRegistry::unregisterByHook()',
            ["argumentsSet('{$listHooksAction}')", "argumentsSet('{$listHooksFilter}')"],
        ],
        'List hooks (deferred) to unregister' => [
            '\\WPLokerBJM\\Core\\Container\\Support\\WPHooksRegistry::unregisterDeferredByHook()',
            ["argumentsSet('{$listHooksAction}')", "argumentsSet('{$listHooksFilter}')"],
        ],
    ];

    foreach ($expectedBlocks as $comment => [$target, $args]) {
        $unit++;
        $renderedArgs = Str\join($args, ",\n        ");
        $result .= "    // Unit #{$unit}: {$comment}\n";
        $result .= "    expectedArguments(\n        {$target},\n        0,\n        {$renderedArgs},\n    );\n\n";
    }

    return Str\trim_right($result, "\n");
}

/**
 * Replace the section between markers with new generated content.
 */
function replaceGeneratedSection(string $content, string $generated): string
{
    $startPos = Str\search($content, MARKER_BEGIN);
    $endPos = Str\search($content, MARKER_END);

    if ($startPos === null || $endPos === null || $startPos >= $endPos) {
        throw new \RuntimeException('Markers not found in ' . MARKER_BEGIN . ' / ' . MARKER_END);
    }

    $before = Str\slice($content, 0, $startPos + Str\length(MARKER_BEGIN));
    $after = Str\slice($content, $endPos);
    return $before . "\n" . $generated . "\n    " . $after;
}

// ── Output helpers ─────────────────────────────────────────────────────────

function info(string $message): void
{
    fwrite(STDERR, "✓  {$message}\n");
}

function warning(string $message): void
{
    fwrite(STDERR, "⚠  {$message}\n");
}

function error(string $message): void
{
    fwrite(STDERR, "✗  {$message}\n");
}
