name                = "wplokerbjm-dev"
main                = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = ["nodejs_compat", "enable_nodejs_http_modules", "enable_nodejs_http_server_modules"]
compatibility_date  = "2026-02-22"
account_id          = "5996bc6e6329a2824240d44bc86bcc03"
route               = "dev.lokerbanjarmasin.my.id/*"
[[kv_namespaces]]
binding             = "wplokerbjm"
id                  = "75fc8b0cd2d74548b6c05321296d4d45"


# needed for adapter-cloudflare: make built assets available to the Worker
[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[dev]
local_protocol = "https"
https-cert-path = "../../../../certs/localhost.crt"
https-key-path = "../../../../certs/localhost.key"

[env]
[env.vars]
PUBLIC_CMS_ORIGIN = "https://dev.lokerbanjarmasin.my.id"
PUBLIC_CMS_ORIGIN_DEV = "https://localhost"