upload_max_filesize = 1024M
post_max_size = 1024M
memory_limit = 8192M
max_execution_time = 300
display_errors = Off
error_reporting = E_ERROR | E_WARNING | E_PARSE
max_input_time=600
file_uploads=On
max_file_uploads=50

; APCu settings
apc.enabled=1
apc.shm_size=512M
apc.ttl=7200
apc.user_ttl=7200
apc.gc_ttl=3600

; Brotli extension settings
brotli.enable=1
brotli.compression_level=11
brotli.compression_mode=generic