[www]

user = wordpress
group = wordpress

listen = /var/run/sock/php-fpm.sock
listen.owner = wordpress
listen.group = wordpress
listen.mode = 0666

pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 2
pm.max_spare_servers = 50
pm.process_idle_timeout = 300s
pm.max_requests = 1000

rlimit_files = 8196
rlimit_core = 0

; Logging
access.log = /proc/self/fd/2
access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"

; PHP settings
;php_admin_value[error_log] = /proc/self/fd/2
php_admin_flag[log_errors] = on

; Security
php_admin_value[disable_functions] = exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source
php_admin_value[open_basedir] = /var/www/html:/tmp:/var/run/sock