<?php

declare(strict_types=1);

namespace WPLokerBJM\Core\Container\Support\WPHooks\Registry;

use Spatie\Backtrace\Backtrace;
use Spatie\Backtrace\Frame;
use ReflectionClass;
use ReflectionFunction;
use ReflectionProperty;
use TargetClass;
use WPLokerBJM\Core\Container\Support\WPHooks\Indexers\EntriesIndexer;
use WPLokerBJM\Core\Container\Support\WPHooks\Trait\HookProviderTrait;
use WPLokerBJM\Shared\Log\Logger;
use Psr\Container\ContainerInterface;
use WPLokerBJM\Core\Container\Support\WPHooks\{ContainerRegistryHandlerEntry, DeferredHookEntryDTO, HookRegistration, HookKey, Provider\WPHookPlanProvider};
use WPLokerBJM\Core\Container\Support\WPHooks\Invoker\{ContainerLazyHookHandler, ContainerLazyPropertyHookHandler};
use WPLokerBJM\Core\Container\Support\WPHooks\Utilities\{HookPattern, HookTagUtilities};
use WPLokerBJM\Core\Container\Support\WPHooks\Abstract\{AnonClassHookMetadata};
use WPLokerBJM\Core\Container\Attributes\{Action, Filter};
use WPLokerBJM\Core\Container\Support\WPHooks\Trait\{DeferredHooksTrait};


/**
 * Registry for WordPress hooks discovered via #[Action] and #[Filter] attributes.
 *
 * Stores all hook registrations as identifiable ContainerLazyHookHandler instances,
 * enabling unregistration by hook name, class, or specific class::method.
 * Service resolution is deferred to hook-fire time (lazy loading).
 * @phpstan-import-type HookType from HookRegistration
 * @phpstan-import-type CallablePlan from HookProviderTrait
 * @phpstan-import-type HookTargetResolve from DeferredHookManager
 * @phpstan-type ActivateEntry \Closure(DeferredHookEntryDTO): bool
 * @template TKey of string

 */
class WPHooksContainerRegistry
{
    /**
     * @var array<TKey<ContainerRegistryHandlerEntry>, ContainerRegistryHandlerEntry>
     */
    public private(set) array $handlers = [];

    public private(set) bool $initialized = false;

    /**
     * deferRegisterUntilHook entries whose trigger hook already fired before
     * initialize(). Processed after registerAll's handler loop so no handler
     * is registered twice.
     *
     * @var list<DeferredHookEntryDTO>
     */
    public private(set) array $pendingDeferredActivation = [];

    /**
     * @param ContainerInterface $container
     * @param HookRegistration[] $hooksRegistration
     * @param WPHookPlanProvider $planProvider Plan provider for condition/hook-name resolution.
     * @param DeferredHookManager $deferredHookManager Deferred hook manager.
     * @param HookTargetResolver $resolverTarget Resolves callable targets to class/method pairs.
     * @param EntriesIndexer $entriesIndexer For fast lookup of handler indexes.
     */
    public function __construct(
        private readonly ContainerInterface $container,
        private array $hooksRegistration,
        private WPHookPlanProvider $planProvider,
        private DeferredHookManager $deferredHookManager,
        private HookTargetResolver $resolverTarget,
        private EntriesIndexer $entriesIndexer
    ) {}

    /**
     * Register all stored hooks with WordPress via add_action/add_filter.
     * @api
     */
    public function initialize(): void
    {
        if ($this->initialized) {
            return;
        }
        $this->registerAll($this->hooksRegistration);
        foreach ($this->handlers as $key => $data) {
            try {
                $data->register();
                $this->entriesIndexer->setIndexes($data);
            } catch (\Exception $e) {
                Logger::error(
                    'WPHooksContainerRegistry',
                    "Error registering {$data->type} '{$data->hook}' for {$key}: {$e->getMessage()}"
                );
            }
        }

        // Trigger hooks that had already fired before boot: activate the
        // entries now that the active pool is fully registered (deferring this
        // avoids double-registering handlers that were activated mid-registerAll).
        foreach ($this->pendingDeferredActivation as $deferredHookEntry) {
            $this->deferredHookManager->activateDeferredByKey($deferredHookEntry, $this->activateEntry);
        }
        $this->pendingDeferredActivation = [];

        $this->initialized = true;
    }

    #region deferred handlers activation methods

    /**
     * Activate all deferred handlers registered for a specific WordPress hook.
     *
     * Moves matching ContainerLazyHookHandler instances from $this->deferredHandlers
     * into $this->handlers and registers them with WordPress via add_action/add_filter.
     * Handlers that have already been activated are silently skipped.
     *
     * **Example:**
     * ```php
     * $registry->activateDeferredByHook('init');
     * ```
     ** types autocomplete DX generated by generate-meta-hooks.php
     * @api
     * @param string $hook WordPress hook name.
     */
    public function activateDeferredByHook(string $hook): void
    {
        $this->deferredHookManager->activateDeferredByHook(
            $hook,
            $this->activateEntry
        );
    }

    /**
     * Activate all deferred handlers belonging to a specific service class.
     *
     * Scans all deferred hooks and activates any ContainerLazyHookHandler whose owning
     * class matches the given FQCN. Already-active handlers are silently skipped.
     *
     * **Example:**
     * ```php
     * $registry->activateDeferredByClass(WPGraphQL::class);
     * ```
     * @api
     * @param class-string $class Fully qualified class name.
     */
    public function activateDeferredByClass(string $class): void
    {
        $this->deferredHookManager->activateDeferredByClass(
            $class,
            $this->activateEntry
        );
    }

    /**
     * Activate deferred hook handlers matching the specified target callable or identifier.
     *
     * Scans the deferred handlers pool and transfers matching entries to the active pool,
     * registering them immediately with WordPress via `add_action()` or `add_filter()`.
     * Works seamlessly across standard instance methods, first-class callables, PHP 8.4
     * property hooks, array targets, and class-string identifiers.
     *
     * Already-activated handlers are silently skipped to prevent duplicate registrations.
     *
     * **Usage Examples:**
     *
     ** 1. First-Class Callable (Recommended for External Orchestrators):
     * Provides full IDE autocompletion, type safety, and static refactoring support.
     * ```php
     *! $registry->activateDeferredByCallable($this->graphQL->setCacheHeader(...));
     * ```
     *
     ** 2. Self-Referencing Array (Recommended for Internal Method Self-Activation):
     * Fast-path resolution when a method manages its own hook status. DRY and refactor-proof via `__FUNCTION__` or `__PROPERTY__`.
     * ```php
     *! $registry->activateDeferredByCallable([$this, __FUNCTION__]);
     *! $registry->activateDeferredByCallable([$this->getParentClass(), $this->parentProperty]);
     * ```
     *
     ** 3. String Identifier (Class::method):**
     * Useful for static activation or when an active instance reference is not readily available.
     * ```php
     *! $registry->activateDeferredByCallable(GraphQLService::class . '::setCacheHeader');
     * ```
     *
     ** 4. Array Lookup (`[$object, 'method']`):**
     * Traditional PHP callable array syntax for instance method target resolution.
     * ```php
     *! $registry->activateDeferredByCallable([$this->graphQL, 'setCacheHeader']);
     * ```
     *
     ** 5. PHP 8.4 Property Hooks & Dynamic Invokables & PHP 8.5 inline closure constant expression:**
     * Activates closures or invokable objects held within class properties.
     * On property: 
     * ```php
     * private $disableNoCacheHeaders = static function() { return false; };
     *
     *! $registry->activateDeferredByCallable($this->graphQL->disableNoCacheHeaders);
     * ```
     *
     * @param HookTargetResolve $target First-class callable, array `[$object, 'method']`,
     *                                  string `'Class::method'`, or invokable property reference.
     * ! active all attribute attached to property or method
     * @api
     * @return void
     * @throws \InvalidArgumentException If the target cannot be resolved to a valid class and member.
     */
    public function activateDeferredByCallable(callable|string|array $target): void
    {
        $this->deferredHookManager->activateDeferredByCallable(
            $target,
            $this->activateEntry
        );
    }

    /**
     * Activate all deferred handlers carrying at least one of the given tags.
     *
     * Scans the deferred handlers pool and transfers matching entries to the
     * active pool, registering them immediately with WordPress. Accepts a
     * single tag string or an array of tags — a hook matches when any of its
     * tags intersects the query set. Already-active handlers are silently
     * skipped.
     *
     * **Example:**
     * ```php
     * $registry->activateDeferredByTags(['cache', 'seo']);
     * $registry->activateDeferredByTags('cache');
     * ```
     * @api
     * @param array<string> $tags Tag or list of tags to activate.
     * @return int Number of handlers activated.
     */
    public function activateDeferredByTags(array $tags): int
    {
        $tags = HookTagUtilities::normalizeTags($tags);

        return $this->deferredHookManager->activateDeferredByTags(
            $tags,
            $this->activateEntry
        );
    }

    /**
     * Activate all deferred handlers belonging to a service namespace.
     *
     * A class matches when it equals the namespace or starts with it followed
     * by a backslash, so 'App\Core' never matches 'App\CoreExtra\Foo'.
     * @api
     * @param string $namespace Fully qualified namespace prefix.
     * @return int Number of handlers activated.
     */
    public function activateDeferredByNamespace(string $namespace): int
    {
        return $this->deferredHookManager->activateDeferredByNamespace(
            $namespace,
            $this->activateEntry
        );
    }

    /**
     * Activate all deferred handlers whose hook name matches a wildcard pattern.
     *
     * The pattern must contain exactly one trailing asterisk with a literal
     * prefix of at least two characters, e.g. 'mail_*'. Already-active
     * handlers are silently skipped.
     * @api
     * @param string $pattern Wildcard hook-name pattern.
     * @return int Number of handlers activated.
     */
    public function activateDeferredByHookPattern(string $pattern): int
    {
        return $this->deferredHookManager->activateDeferredByHookPattern(
            $pattern,
            $this->activateEntry
        );
    }

    /**
     * Activate all deferred handlers carrying at least one tag matching any of
     * the given wildcard patterns.
     *
     * Each pattern is its own tag family to wipe: an entry matches when any of
     * its tags matches any pattern (union of families).
     * @api
     * @param array<string> $patterns Tag wildcard patterns.
     * @return int Number of handlers activated.
     */
    public function activateDeferredByTagPattern(array $patterns): int
    {
        return $this->deferredHookManager->activateDeferredByTagPattern(
            $patterns,
            $this->activateEntry
        );
    }
    #endregion

    #region deferred handlers unregisteration methods
    /**
     * Unregister a deferred hook using a first-class callable, array lookup,
     * or class-string identifier.
     * ! sweep all attribute attached to property or method
     * @param HookTargetResolve $target
     * @api
     */
    public function unregisterDeferredByCallable(callable|string|array $target): void
    {
        $this->deferredHookManager->unregisterDeferredByCallable($target);
    }

    /**
     * Unregister all deferred handlers for a specific WordPress hook name.
     * @api
     * @param string $hook WordPress hook name.
     */
    public function unregisterDeferredByHook(string $hook): void
    {
        $this->deferredHookManager->unregisterDeferredByHook($hook);
    }

    /**
     * Unregister all deferred hooks belonging to a specific service class.
     * @api
     * @param class-string $class Fully qualified class name.
     */
    public function unregisterDeferredByClass(string $class): void
    {
        $this->deferredHookManager->unregisterDeferredByClass($class);
    }

    /**
     * Unregister all deferred hooks belonging to a service namespace.
     *
     * Only touches the deferred pool — active handlers are never affected.
     * @api
     * @param string $namespace Fully qualified namespace prefix.
     */
    public function unregisterDeferredByNamespace(string $namespace): void
    {
        $this->deferredHookManager->unregisterDeferredByNamespace($namespace);
    }

    /**
     * Unregister all deferred handlers carrying at least one of the given tags.
     *
     * Only touches the deferred pool — active handlers are never affected.
     * Accepts a single tag string or an array of tags; a hook matches when any
     * of its tags intersects the query set.
     * @api
     * @param array<string> $tags Tag or list of tags to unregister.
     */
    public function unregisterDeferredByTags(array $tags): void
    {
        $this->deferredHookManager->unregisterDeferredByTags(HookTagUtilities::normalizeTags($tags));
    }

    /**
     * Unregister all deferred handlers whose hook name matches a wildcard pattern.
     *
     * Only touches the deferred pool — active handlers are never affected.
     * @example ```php
     * $registry->unregisterDeferredByHookPattern('graphql_*')
     * ```
     * @api
     * @param string $pattern Wildcard hook-name pattern (see HookPattern).
     */
    public function unregisterDeferredByHookPattern(string $pattern): void
    {
        $this->deferredHookManager->unregisterDeferredByHookPattern($pattern);
    }

    /**
     * Unregister all deferred handlers carrying at least one tag matching any
     * of the given wildcard patterns.
     *
     * Only touches the deferred pool — active handlers are never affected.
     * @example ```php
     * $registry->unregisterDeferredByTagPattern(['graphql_*', 'theme_*', 'woocommerce_*'])
     * ```
     * @api
     * each entry in array is its own family to to unregister
     * @param array<string> $patterns Tag wildcard patterns.
     */
    public function unregisterDeferredByTagPattern(array $patterns): void
    {
        $this->deferredHookManager->unregisterDeferredByTagPattern($patterns);
    }
    #endregion
    #region main handlers unregisteration methods
    /**
     * Unregister a registered hook via first-class callable, array lookup,
     * or class-string identifier.
     * ! sweep all attribute attached to property or method
     * @api
     * @param HookTargetResolve $target
     */
    public function unregisterByCallable(callable|string|array $target): void
    {
        $keyCallable = $this->entriesIndexer->getCallable($this->resolverTarget->resolve($target));
        $entries = $this->entriesIndexer->byCallable[$keyCallable] ?? [];
        foreach ($entries as $uniqueKey) {
            $this->handlers[$uniqueKey]->unregister();
            unset($this->handlers[$uniqueKey]);
        }
        unset($this->entriesIndexer->byCallable[$keyCallable]);
    }

    /**
     * Unregister all handlers for a specific WordPress hook name.
     * @api 
     * @param string $hook WordPress hook name.
     */
    public function unregisterByHook(string $hook): void
    {
        $entries = $this->entriesIndexer->byHook[$hook] ?? [];
        foreach ($entries as $uniqueKey) {
            $this->handlers[$uniqueKey]->unregister();
            unset($this->handlers[$uniqueKey]);
        }
        unset($this->entriesIndexer->byHook[$hook]);
    }

    /**
     * Unregister all hooks belonging to a specific service class.
     * @api
     * @param class-string $class Fully qualified class name.
     */
    public function unregisterByClass(string $class): void
    {
        $entries = $this->entriesIndexer->byClass[$class] ?? [];
        foreach ($entries as $uniqueKey) {
            $this->handlers[$uniqueKey]->unregister();
            unset($this->handlers[$uniqueKey]);
        }
        unset($this->entriesIndexer->byClass[$class]);
    }

    /**
     * Unregister all active hooks belonging to a service namespace.
     *
     * Only touches the active pool — deferred handlers are never affected.
     * A class matches when it equals the namespace or starts with it followed
     * by a backslash, so 'App\Core' never matches 'App\CoreExtra\Foo'.
     * @api 
     * @param string $namespace Fully qualified namespace prefix.
     */
    public function unregisterByNamespace(string $namespace): void
    {
        $entries = $this->entriesIndexer->byNamespace[$namespace] ?? [];
        foreach ($entries as $uniqueKey) {
            if (!isset($this->handlers[$uniqueKey])) {
                continue;
            }
            $this->handlers[$uniqueKey]->unregister();
            unset($this->handlers[$uniqueKey]);
        }
        unset($this->entriesIndexer->byNamespace[$namespace]);
    }

    /**
     * Unregister all active handlers carrying at least one of the given tags.
     *
     * Only touches the active pool — deferred handlers are never affected.
     * Accepts a single tag string or an array of tags; a hook matches when any
     * of its tags intersects the query set.
     * @api
     * @param array<string> $tags Tag or list of tags to unregister.
     */
    public function unregisterByTags(array $tags): void
    {
        $tags = HookTagUtilities::normalizeTags($tags);

        if ($tags === []) {
            return;
        }

        foreach ($tags as $tag) {
            $entries = $this->entriesIndexer->byTag[$tag] ?? [];
            if (empty($entries)) {
                continue;
            }

            foreach ($entries as $key) {
                if (!isset($this->handlers[$key])) {
                    continue;
                }
                $this->handlers[$key]->unregister();
                unset($this->handlers[$key]);
            }
            unset($this->entriesIndexer->byTag[$tag]);
        }
    }

    /**
     * Unregister all active handlers whose hook name matches a wildcard pattern.
     *
     * Only touches the active pool — deferred handlers are never affected.
     * @example ```php
     * $registry->unregisterByHookPattern('graphql_*')
     * ```
     * @api
     * @param string $pattern Wildcard hook-name pattern (see HookPattern).
     */
    public function unregisterByHookPattern(string $pattern): void
    {
        HookPattern::assertValid($pattern);
        $hooks = $this->entriesIndexer->byHook;
        foreach ($hooks as $hook => $uniqueKeys) {
            foreach ($uniqueKeys as $uniqueKey) {
                if (!HookPattern::matches($hook, $pattern)) {
                    continue;
                }
                $this->handlers[$uniqueKey]->unregister();
                unset($this->handlers[$uniqueKey]);
            }
            unset($this->entriesIndexer->byHook[$hook]);
        }
    }

    /**
     * Unregister all active handlers carrying at least one tag matching any of
     * the given wildcard patterns.
     *
     * Only touches the active pool — deferred handlers are never affected.
     * @example ```php
     * $registry->unregisterByTagPattern(['graphql_*', 'theme_*', 'woocommerce_*'])
     * ```
     * @api
     * each entry in array is its own family to to unregister
     * @param array<string> $patterns Tag wildcard patterns.
     */
    public function unregisterByTagPattern(array $patterns): void
    {
        if ($patterns === []) {
            return;
        }
        HookPattern::assertValidAll($patterns);
        $entries = $this->entriesIndexer->byTag;
        foreach ($entries as $tag => $uniqueKeys) {
            foreach ($uniqueKeys as $uniqueKey) {
                $handler = $this->handlers[$uniqueKey] ?? null;
                if ($handler && !HookPattern::matchesAny($handler->tags, $patterns)) {
                    continue;
                }
                $this->handlers[$uniqueKey]->unregister();
                unset($this->handlers[$uniqueKey]);
            }
            unset($this->entriesIndexer->byTag[$tag]);
        }
    }
    #endregion

    /**
     * Callback provided to the DeferredHookManager: moves a deferred entry into
     * the active pool and registers it with WordPress.
     * @var ActivateEntry
     */
    private \Closure $activateEntry {
        get => $this->activateEntry ??= function (DeferredHookEntryDTO $data): bool {
            // Guard: skip if already activated
            $uniqueKey = $data->toUniqueKey();
            if (isset($this->handlers[$uniqueKey])) {
                return false;
            }
            $entry = $this->handlers[$uniqueKey] = ContainerRegistryHandlerEntry::fromDeferredEntry($data);

            $entry->register();

            return true;
        };
    }

    /**
     * @Internal remove a once-registration from the active pool after its
     * first fire (consume-on-any-evaluation). Idempotent.
     */
    private function removeOnceEntry(ContainerRegistryHandlerEntry $entry): void
    {
        $uniqueKey = $entry->toUniqueKey();
        if (!isset($this->handlers[$uniqueKey])) {
            return;
        }

        $entry = $this->handlers[$uniqueKey];
        // Skip the WordPress-side removal while the hook is being dispatched:
        // remove_action during dispatch corrupts WP_Hook's iteration
        // (resort_active_iterations skips the immediately-following priority).
        // The consumed flag already prevents re-firing, so the callback can
        // safely linger in $wp_filter until the request ends.
        !$entry->stillInCallbackStack() && $entry->unregister();

        unset($this->handlers[$uniqueKey]);
    }

    /**
     * Register hook registrations from the scanner.
     * Pre-builds ContainerLazyHookHandler instances and validates container existence.
     *
     * @param list<HookRegistration> $registrations
     */
    private function registerAll(array $registrations): void
    {
        foreach ($registrations as $reg) {
            $registration = $reg instanceof HookRegistration ? $reg : HookRegistration::fromArray($reg);

            if (!$this->container->has($registration->class)) {
                Logger::warning(
                    'WPHooksContainerRegistry',
                    'Skipping hook ' . $registration->hook
                        . ' — class not in container: ' . $registration->class
                );
                continue;
            }

            try {
                $hookName = $this->planProvider->resolveHookName(
                    $registration->hook,
                    $this->container,
                    $registration->hookParams,
                    $registration->class . '::' . $registration->method
                );
            } catch (\RuntimeException $e) {
                Logger::error(
                    'WPHooksContainerRegistry',
                    'Skipping hook for ' . $registration->class . '::' . $registration->method
                        . ' on ' . ($registration->hook instanceof \Closure ? '(closure)' : $registration->hook)
                        . ' — ' . $e->getMessage()
                );
                continue;
            }

            // Registration gate: evaluated ONCE at activiation time — a false
            // result means the hook is never registered.
            // Entries carrying deferRegisterUntilHook skip this gate entirely:
            // they defer to the named trigger hook, where the gate is evaluated
            // at activation time (when request context exists).
            if ($registration->deferRegisterUntilHook === null) {
                try {
                    $allowed = $this->planProvider->evaluateRegistrationGate(
                        $registration->registerIf,
                        $registration->registerIfParams,
                        $this->container,
                        $registration->class . '::' . $registration->method,
                        $registration->class
                    );
                } catch (\Throwable $e) {
                    Logger::error(
                        'WPHooksContainerRegistry',
                        'Skipping hook for ' . $registration->class . '::' . $registration->method . ' on ' . $hookName . ' — ' . $e->getMessage()
                    );
                    continue;
                }
                if (!$allowed) {
                    Logger::warning(
                        'WPHooksContainerRegistry',
                        'Skipping hook ' . $registration->class . '::' . $registration->method . ' on ' . $hookName . ' — registerIf gate returned false.'
                    );
                    continue;
                }
            }

            // Resolve dynamic tags: the attribute accepts either a static tag
            // list or a single callable returning the full resolved list.
            // Entries are normalized to strings (string | string-backed enum).
            try {
                if ($registration->tagCallable !== null) {
                    $resolvedTags = $this->planProvider->resolveTagCallable(
                        $registration->tagCallable,
                        $registration->tagCallableParams ?? [],
                        $this->container,
                        $registration->class . '::' . $registration->method,
                        $registration->class
                    );
                } else {
                    $resolvedTags = $registration->tags;
                }

                $resolvedTags = array_map(
                    static fn($tag) => HookTagUtilities::normalizeTagValue($tag),
                    $resolvedTags
                );
            } catch (\Throwable $e) {
                Logger::error(
                    'WPHooksContainerRegistry',
                    'Skipping hook for ' . $registration->class . '::' . $registration->method
                        . ' on ' . $hookName . ' — ' . $e->getMessage()
                );
                continue;
            }
            $entry = new ContainerRegistryHandlerEntry(
                hook: $hookName,
                key: HookKey::fromRegistration($registration),
                handler: $registration->target === 'method'
                    ? new ContainerLazyHookHandler($this->container, $registration->class, $registration->method, $registration->visibility, $registration->type, $registration->executeIf, $registration->executeIfParams, $this->planProvider, $registration->hookArgs, $registration->once)
                    : new ContainerLazyPropertyHookHandler($this->container, $registration->class, $registration->method, $registration->visibility, $registration->type, $registration->executeIf, $registration->executeIfParams, $this->planProvider, $registration->hookArgs, $registration->once),
                type: $registration->type,
                priority: $registration->priority,
                acceptedArgs: $registration->acceptedArgs,
                tags: $resolvedTags,
                registerIf: $registration->registerIf,
                registerIfParams: $registration->registerIfParams,
                executeIf: $registration->executeIf,
                executeIfParams: $registration->executeIfParams,
                once: $registration->once,
            );

            if ($registration->once) {
                $entry->handler->setRemoveCallback(
                    fn() => $this->removeOnceEntry($entry)
                );
            }

            // deferRegisterUntilHook implies deferral: the entry is held in the
            // deferred pool until the trigger hook fires, regardless of how the
            // registration array was built (attribute, scanner cache, runtime).
            if ($registration->deferRegister || $registration->deferRegisterUntilHook !== null) {
                $recordEntry = $entry->toDeferredEntryDTO();
                $this->deferredHookManager->addDeferred($recordEntry);

                if ($registration->deferRegisterUntilHook !== null) {
                    $triggerHook = $registration->deferRegisterUntilHook;
                    if ($triggerHook instanceof \Closure) {
                        try {
                            $triggerHook = $this->planProvider->resolveHookName(
                                $registration->deferRegisterUntilHook,
                                $this->container,
                                $registration->deferRegisterUntilHookParams ?? [],
                                $registration->class . '::' . $registration->method
                            );
                        } catch (\RuntimeException $e) {
                            Logger::error(
                                'WPHooksContainerRegistry',
                                'Skipping hook for ' . $registration->class . '::' . $registration->method . ' on ' . $hookName . ' — ' . $e->getMessage()
                            );
                            continue;
                        }
                    }
                    $this->scheduleDeferredActivation(
                        $triggerHook,
                        $recordEntry
                    );
                }
            } else {
                $this->handlers[$entry->toUniqueKey()] = $entry;
            }
        }
    }

    /**
     * Schedule one-shot activation of a deferRegisterUntilHook entry when the
     * trigger hook fires. If the trigger already fired (did_action), the entry
     * is activated immediately.
     *
     * The listener stays attached while the gates keep failing, so a later
     * fire of the trigger hook gets another chance. Once activation succeeds
     * the listener removes itself.
     *
     * @param string $triggerHook WordPress hook that gates activation.
     */
    private function scheduleDeferredActivation(string $triggerHook, DeferredHookEntryDTO $entry): void
    {

        if (did_action($triggerHook)) {
            $this->pendingDeferredActivation[] = $entry;
            return;
        }

        $listener = function () use ($triggerHook, $entry): void {
            $activated = $this->deferredHookManager->activateDeferredByKey($entry, $this->activateEntry);

            $activated && remove_action($triggerHook, \Closure::getCurrent(), PHP_INT_MIN);
        };

        add_action($triggerHook, $listener, PHP_INT_MIN, 0);
    }
}
/**
 * @internal not for external use beyond @see WPHooksContainerRegistry
 * 
 * @template TargetClass
 * @phpstan-type HookTargetResolve callable|string|array{class-string<TargetClass>&object<TargetClass>, callable-string<TargetClass>}
 * @phpstan-import-type CallablePlan from HookProviderTrait
 * @phpstan-import-type CallableHookParams from HookProviderTrait
 * @phpstan-import-type HookType from HookRegistration
 * @phpstan-import-type DeferredHookEntry from DeferredHooksTrait
 * @phpstan-import-type ActivateEntry from WPHooksContainerRegistry
 */
class DeferredHookManager
{
    use DeferredHooksTrait;

    /**
     * @param WPHookPlanProvider  $planProvider Plan provider used for registerIf gates.
     * @param ContainerInterface $container    Container used by gate closures.
     * @param HookTargetResolver $resolverTarget 
     * @param EntriesIndexer $entriesIndexer for fast lookup of matching entries
     */
    public function __construct(
        private WPHookPlanProvider $planProvider,
        private ContainerInterface $container,
        private HookTargetResolver $resolverTarget,
        private EntriesIndexer $entriesIndexer
    ) {}

    /**
     * Activate all deferred handlers registered for a specific WordPress hook.
     *
     * @param ActivateEntry $activateEntry Registry callback: moves the
     *                                                             entry to the active pool and
     *                                                             registers it; returns true when
     *                                                             newly activated, false when the
     *                                                             handler was already active.
     */
    public function activateDeferredByHook(string $hook, \Closure $activateEntry): void
    {
        $this->activateMatchingDeferredEntries(
            $this->entriesIndexer->byHook[$hook] ?? [],
            $activateEntry,
        );
    }

    /**
     * Activate all deferred handlers belonging to a specific service class.
     *
     * @param class-string $class Fully qualified class name.
     * @param ActivateEntry $activateEntry Registry callback (see activateDeferredByHook).
     */
    public function activateDeferredByClass(string $class, \Closure $activateEntry): void
    {
        $this->activateMatchingDeferredEntries(
            $this->entriesIndexer->byClass[$class] ?? [],
            $activateEntry,
        );
    }

    /**
     * Activate all deferred handlers belonging to a service namespace.
     *
     * A class matches when it equals the namespace or starts with it followed
     * by a backslash, so 'App\Core' never matches 'App\CoreExtra\Foo'.
     *
     * @param string $namespace Fully qualified namespace prefix.
     * @param ActivateEntry $activateEntry Registry callback (see activateDeferredByHook).
     * @return int Number of handlers activated.
     */
    public function activateDeferredByNamespace(string $namespace, \Closure $activateEntry): int
    {
        $entries = $this->entriesIndexer->byNamespace[$namespace] ?? [];
        $keys = [];
        foreach ($entries as $key) {
            $keys[] = $key;
        }
        return $this->activateMatchingDeferredEntries(
            $keys,
            $activateEntry,
        );
    }

    /**
     * Activate deferred hook handlers matching the specified target callable or identifier.
     *
     * @param HookTargetResolve $target
     * @param ActivateEntry $activateEntry Registry callback (see activateDeferredByHook).
     *
     * @throws \InvalidArgumentException If the target cannot be resolved to a valid class and member.
     */
    public function activateDeferredByCallable(callable|string|array $target, \Closure $activateEntry): void
    {
        $key = $this->entriesIndexer->getCallable($this->resolverTarget->resolve($target));

        $this->activateMatchingDeferredEntries(
            $this->entriesIndexer->byCallable[$key] ?? [],
            $activateEntry,
        );
    }

    /**
     * Activate all deferred handlers carrying at least one of the given tags.
     *
     * @param array<string> $tags Tag or list of tags to activate.
     * @param ActivateEntry $activateEntry Registry callback (see activateDeferredByHook).
     * @return int Number of handlers activated.
     */
    public function activateDeferredByTags(array $tags, \Closure $activateEntry): int
    {
        if ($tags === []) {
            return 0;
        }

        $keys = [];

        foreach ($tags as $tag) {
            $entries = $this->entriesIndexer->byTag[$tag] ?? [];
            foreach ($entries as $key) {
                $entry = $this->deferredHandlers[$key] ?? null;
                if (! isset($entry)) {
                    continue;
                }
                if (\array_intersect($tags, $entry->tags) !== []) {
                    $keys[] = $key;
                }
            }
        }

        return $this->activateMatchingDeferredEntries(
            $keys,
            $activateEntry,
        );
    }

    /**
     * Activate all deferred handlers whose hook name matches a wildcard pattern.
     *
     * The pattern must contain exactly one trailing asterisk with a literal
     * prefix of at least two characters, e.g. 'mail_*'. Already-active
     * handlers are silently skipped.
     *
     * @param string $pattern Wildcard hook-name pattern.
     * @param ActivateEntry $activateEntry Registry callback (see activateDeferredByHook).
     * @return int Number of handlers activated.
     */
    public function activateDeferredByHookPattern(string $pattern, \Closure $activateEntry): int
    {
        HookPattern::assertValid($pattern);
        $hooks = $this->entriesIndexer->byHook;
        $keys = [];
        foreach ($hooks as $hook) {
            foreach ($hook as $key) {
                $entry = $this->deferredHandlers[$key] ?? null;
                if ($entry === null) {
                    continue;
                }
                if (HookPattern::matches($entry->hook, $pattern)) {
                    $keys[] = $key;
                }
            }
        }

        return $this->activateMatchingDeferredEntries(
            $keys,
            $activateEntry,
        );
    }

    /**
     * Activate all deferred handlers carrying at least one tag matching any of
     * the given wildcard patterns.
     *
     * Each pattern is its own tag family to wipe: an entry matches when any of
     * its tags matches any pattern (union of families).
     *
     * @param array<string> $patterns Tag wildcard patterns.
     * @param ActivateEntry $activateEntry Registry callback (see activateDeferredByHook).
     * @return int Number of handlers activated.
     */
    public function activateDeferredByTagPattern(array $patterns, \Closure $activateEntry): int
    {
        if ($patterns === []) {
            return 0;
        }
        HookPattern::assertValidAll($patterns);
        $entries = $this->entriesIndexer->byTag;
        $keys = [];
        foreach ($entries as $key => $value) {
            foreach ($value as $entry) {
                if (HookPattern::matchesAny($this->deferredHandlers[$entry]->tags, $patterns)) {
                    $keys[] = $entry;
                }
            }
        }

        return $this->activateMatchingDeferredEntries(
            $keys,
            $activateEntry,
        );
    }

    /**
     * Activate a single deferred handler by exact hook + key.
     *
     * One-shot entry point for deferRegisterUntilHook entries: the trigger
     * hook listener calls this when the trigger fires. registerIf is
     * re-evaluated as with every activation.
     * @internal
     * @param ActivateEntry $activateEntry Registry callback (see activateDeferredByHook).
     * @return bool True when the entry was newly activated; false when the
     *              entry is unknown, already active, or a gate rejected it.
     */
    public function activateDeferredByKey(DeferredHookEntryDTO $deferredHookEntry, \Closure $activateEntry): bool
    {
        $uniqueKey = $deferredHookEntry->toUniqueKey();
        if (!isset($this->deferredHandlers[$uniqueKey])) {
            return false;
        }

        $data = $this->deferredHandlers[$uniqueKey];

        // Registration gate: re-evaluated at activation time.
        if (!$this->gateDeferredActivation($data)) {
            return false;
        }

        $activated = $activateEntry($data);

        unset($this->deferredHandlers[$uniqueKey]);

        return $activated;
    }

    /**
     * Unregister a deferred hook using a first-class callable, array lookup,
     * or class-string identifier.
     *
     * @param HookTargetResolve $target
     */
    public function unregisterDeferredByCallable(callable|string|array $target): void
    {
        $keyCallable = $this->entriesIndexer->getCallable($this->resolverTarget->resolve($target));
        $entries = $this->entriesIndexer->byCallable[$keyCallable] ?? [];
        foreach ($entries as $key) {
            if (!isset($this->deferredHandlers[$key])) {
                continue;
            }
            unset($this->deferredHandlers[$key]);
        }
        unset($this->entriesIndexer->byCallable[$keyCallable]);
    }

    /**
     * Unregister all deferred handlers for a specific WordPress hook name.
     *
     * @param string $hook WordPress hook name.
     */
    public function unregisterDeferredByHook(string $hook): void
    {
        $entries = $this->entriesIndexer->byHook[$hook] ?? [];
        foreach ($entries as $key) {
            if (!isset($this->deferredHandlers[$key])) {
                continue;
            }
            unset($this->deferredHandlers[$key]);
        }
        unset($this->entriesIndexer->byHook[$hook]);
    }

    /**
     * Unregister all deferred hooks belonging to a specific service class.
     *
     * @param class-string $class Fully qualified class name.
     */
    public function unregisterDeferredByClass(string $class): void
    {
        $entries = $this->entriesIndexer->byClass[$class] ?? [];
        foreach ($entries as $key) {
            if (!isset($this->deferredHandlers[$key])) {
                continue;
            }
            unset($this->deferredHandlers[$key]);
        }
        unset($this->entriesIndexer->byClass[$class]);
    }

    /**
     * Unregister all deferred hooks belonging to a service namespace.
     *
     * Only touches the deferred pool — active handlers are never affected.
     * A class matches when it equals the namespace or starts with it followed
     * by a backslash.
     *
     * @param string $namespace Fully qualified namespace prefix.
     */
    public function unregisterDeferredByNamespace(string $namespace): void
    {
        $entries = $this->entriesIndexer->byNamespace[$namespace] ?? [];
        foreach ($entries as $key) {
            $handler = $this->deferredHandlers[$key] ?? null;
            if ($handler && !$handler->key->isWithinNamespace($namespace)) {
                continue;
            }
            unset($this->deferredHandlers[$key]);
        }
        unset($this->entriesIndexer->byNamespace[$namespace]);
    }

    /**
     * Unregister all deferred handlers carrying at least one of the given tags.
     *
     * Only touches the deferred pool — active handlers are never affected.
     *
     * @param array<string> $tags Tag or list of tags to unregister.
     */
    public function unregisterDeferredByTags(array $tags): void
    {
        if ($tags === []) {
            return;
        }
        foreach ($tags as $tag) {
            $entries = $this->entriesIndexer->byTag[$tag] ?? [];
            if (empty($entries)) {
                continue;
            }

            foreach ($entries as $key) {
                if (!isset($this->deferredHandlers[$key])) {
                    continue;
                }
                unset($this->deferredHandlers[$key]);
            }
            unset($this->entriesIndexer->byTag[$tag]);
        }
    }

    /**
     * Unregister all deferred handlers whose hook name matches a wildcard pattern.
     *
     * Only touches the deferred pool — active handlers are never affected.
     *
     * @param string $pattern Wildcard hook-name pattern (see HookPattern).
     */
    public function unregisterDeferredByHookPattern(string $pattern): void
    {
        HookPattern::assertValid($pattern);
        $hooks = $this->entriesIndexer->byHook ?? [];
        foreach ($hooks as $hook) {
            foreach ($hook as $key) {
                $entry = $this->deferredHandlers[$key] ?? null;
                if (!($entry instanceof DeferredHookEntryDTO)) continue;
                if (HookPattern::matches($entry->hook, $pattern)) {
                    unset($this->deferredHandlers[$key]);
                    unset($this->entriesIndexer->byHook[$key]);
                }
            }
        }
    }

    /**
     * Unregister all deferred handlers carrying at least one tag matching any
     * of the given wildcard patterns.
     *
     * Only touches the deferred pool — active handlers are never affected.
     *
     * @param array<string> $patterns Tag wildcard patterns.
     */
    public function unregisterDeferredByTagPattern(array $patterns): void
    {
        if ($patterns === []) {
            return;
        }
        HookPattern::assertValidAll($patterns);
        $tags = $this->entriesIndexer->byTag ?? [];
        foreach ($tags as $tag) {
            foreach ($tag as $key) {
                $entry = $this->deferredHandlers[$key] ?? null;
                if (!($entry instanceof DeferredHookEntryDTO)) continue;
                if (HookPattern::matchesAny($entry->tags, $patterns)) {
                    unset($this->deferredHandlers[$key]);
                    unset($this->entriesIndexer->byTag[$key]);
                }
            }
        }
    }

    /**
     * Re-evaluate the registerIf registration gate when activating a deferred hook.
     *
     * The gate was already evaluated once in registerAll(); activation is the
     * moment the hook actually registers with WordPress, so it is re-checked
     * here. On failure the entry stays in the deferred pool (a later activation
     * attempt may succeed once the gate flips to true except if 'once' is true).
     *
     * @param DeferredHookEntryDTO $data Handler entry.
     */
    private function gateDeferredActivation(DeferredHookEntryDTO $data): bool
    {
        if (($data->registerIf ?? null) === null) {
            return true;
        }

        try {
            $allowed = $this->planProvider->evaluateRegistrationGate(
                $data->registerIf,
                $data->registerIfParams ?? [],
                $this->container,
                $data->toUniqueKey(),
                $data->key->class
            );
        } catch (\Throwable $e) {
            Logger::error(
                'WPHooksContainerRegistry',
                'Skipping deferred hook activation ' . $data->hook . ' — ' . $e->getMessage()
            );
            return false;
        }

        if (!$allowed) {
            Logger::warning(
                'WPHooksContainerRegistry',
                'Skipping deferred hook activation ' . $data->hook . ' — registerIf gate returned false.'
            );
            return false;
        }

        return true;
    }
}
/**
 * @internal not for use beyond \WPLokerBJM\Core\Container\Support\WPHooks\Registry\
 * @template TClass
 * @phpstan-import-type HookTargetResolve from DeferredHookManager
 */
class HookTargetResolver
{
    /**
     * Per-request cache of resolved callable → [FQCN, memberName].
     *
     * WeakMap automatically drops entries when their key (the callable
     * object) is garbage-collected, avoiding memory leaks.
     *
     * @var \WeakMap<object<TClass>, array{class-string<TClass>, callable-string<TClass>}>
     */
    private \WeakMap $callableTargetCache { get => $this->callableTargetCache ??= new \WeakMap(); }

    /**
     * @param HookTargetResolve $target
     * @return array{class-string<TClass>, callable-string<TClass>}
     */
    public function resolve(object|callable|array|string $target): array
    {
        if (is_object($target) && isset($this->callableTargetCache[$target])) {
            return $this->callableTargetCache[$target];
        }

        $result = $this->doResolveCallableTarget($target);

        if (is_object($target)) {
            $this->callableTargetCache[$target] = $result;
        }
        return $result;
    }

    /**
     * @param HookTargetResolve $target
     * @return array{class-string<TClass>, callable-string<TClass>}
     */
    private function doResolveCallableTarget(object|callable|array|string $target): array
    {
        // 1. Array [$object, 'memberName'] — fast path
        if (is_array($target)) {
            if (is_object($target[0])) {
                return [get_class($target[0]), $target[1]];
            } elseif (is_string($target[0])) {
                return [$target[0], $target[1]];
            }
        }

        // 2. String 'Class::method' — static fallback
        if (is_string($target)) {
            $parts = explode('::', $target, 2);
            return [$parts[0], $parts[1] ?? '__invoke'];
        }

        // 3. Invokable Object Instance (anonymous class from a property)
        if (!$target instanceof \Closure && is_object($target)) {
            return $this->analyseObject($target);
        }

        // 4. Closure (First-class callable or PHP 8.4 property hook accessor)
        $ref = new \ReflectionFunction($target);
        $calledClass = $ref->getClosureThis() ?? null;

        if ($calledClass === null) {
            throw new \InvalidArgumentException('Callable target must be bound to an object instance.');
        }

        $name = $ref->getName();

        // Standard Instance Method ($service->method(...))
        if (!str_contains($name, '{closure')) {
            return [$calledClass::class, $name];
        }

        // PHP 8.4 Property Hook Closure ("{closure:FQCN::$propertyName::get():line}")
        if (str_contains($name, '::$')) {
            $start = strpos($name, '::$') + 3;
            $end = strpos($name, '::', $start);

            if ($start !== false && $end !== false) {
                return [$calledClass::class, substr($name, $start, $end - $start)];
            }
        }

        throw new \InvalidArgumentException('Unable to resolve hook target for class ' . $calledClass::class . '.');
    }

    /**
     * @param object<TClass> $target
     * @return array{class-string<TClass>, callable-string<TClass>}
     */
    private function analyseObject(object $target): array
    {
        $className = $target::class;

        // Anonymous class extending AnonClassHookMetadata —
        // reads parent class & property directly, no backtrace needed.
        if ($target instanceof AnonClassHookMetadata) {
            return [$target->getParentClass(), $target->parentProperty];
        }

        // Best-effort fallback for anonymous classes: walk the call stack
        // to find which object's property holds this instance.
        if ((new \ReflectionClass($target))->isAnonymous()) {
            $frames = Backtrace::create()
                ->withArguments(false)
                ->limit(10)
                ->frames();

            /** @var Frame $frame */
            foreach ($frames as $frame) {
                $callerObject = $frame->object;
                if ($callerObject === null) {
                    continue;
                }

                $refClass = new \ReflectionClass($callerObject);
                foreach ($refClass->getProperties() as $property) {
                    if ($property->isInitialized($callerObject) && $property->getValue($callerObject) === $target) {
                        Logger::warning(
                            "WPHooksContainerRegistry: ",
                            "Anon class without extending AnonClassHookMetadata, it's recommended to use 'AnonClassHookMetadata'." . $refClass->getName() . "::" . $property->getName()
                        );
                        return [$refClass->getName(), $property->getName()];
                    }
                }
            }
        }

        return [$className, '__invoke'];
    }
}
